"""
Mumbai Suburban Railway Network Master Data.
Includes all operational corridors:
1. Western Line (Churchgate <-> Virar)
2. Central Main Line (CSMT <-> Kalyan)
3. Central Line Extensions:
   a. Kalyan <-> Kasara
   b. Kalyan <-> Karjat
   c. Karjat <-> Khopoli
4. Harbour Line (CSMT <-> Panvel)
5. Trans-Harbour Line (Thane <-> Vashi / Nerul / Panvel)
6. Nerul / Belapur <-> Uran Suburban Corridor (Port Line Phase 2)
"""

# Unique station master dictionary keyed by canonical official station code
MUMBAI_SUBURBAN_STATIONS = [
    # ==========================================
    # WESTERN LINE STATIONS (Churchgate -> Virar)
    # ==========================================
    {
        "code": "CCG",
        "name": "Churchgate",
        "city": "Mumbai",
        "state": "Maharashtra",
        "district": "Mumbai City",
        "zone": "WR",
        "division": "Mumbai WR",
        "station_type": "SUBURBAN",
        "corridors": "Western Line",
        "search_aliases": "churchgate, ccg, south mumbai",
        "is_major": True,
        "is_junction": False,
        "platform_count": 4,
        "latitude": 18.9322,
        "longitude": 72.8264,
    },
    {
        "code": "MEL",
        "name": "Marine Lines",
        "city": "Mumbai",
        "state": "Maharashtra",
        "district": "Mumbai City",
        "zone": "WR",
        "division": "Mumbai WR",
        "station_type": "SUBURBAN",
        "corridors": "Western Line",
        "search_aliases": "marine lines, mel",
        "is_major": False,
        "is_junction": False,
        "platform_count": 4,
        "latitude": 18.9443,
        "longitude": 72.8236,
    },
    {
        "code": "CYR",
        "name": "Charni Road",
        "city": "Mumbai",
        "state": "Maharashtra",
        "district": "Mumbai City",
        "zone": "WR",
        "division": "Mumbai WR",
        "station_type": "SUBURBAN",
        "corridors": "Western Line",
        "search_aliases": "charni road, cyr, girgaon chowpatty",
        "is_major": False,
        "is_junction": False,
        "platform_count": 4,
        "latitude": 18.9518,
        "longitude": 72.8189,
    },
    {
        "code": "GTR",
        "name": "Grant Road",
        "city": "Mumbai",
        "state": "Maharashtra",
        "district": "Mumbai City",
        "zone": "WR",
        "division": "Mumbai WR",
        "station_type": "SUBURBAN",
        "corridors": "Western Line",
        "search_aliases": "grant road, gtr",
        "is_major": False,
        "is_junction": False,
        "platform_count": 4,
        "latitude": 18.9629,
        "longitude": 72.8156,
    },
    {
        "code": "MMCT",
        "name": "Mumbai Central",
        "city": "Mumbai",
        "state": "Maharashtra",
        "district": "Mumbai City",
        "zone": "WR",
        "division": "Mumbai WR",
        "station_type": "SUBURBAN",
        "corridors": "Western Line",
        "search_aliases": "mumbai central, mmct, bct, bcl, bombay central",
        "is_major": True,
        "is_junction": True,
        "platform_count": 8,
        "latitude": 18.9696,
        "longitude": 72.8193,
    },
    {
        "code": "MX",
        "name": "Mahalaxmi",
        "city": "Mumbai",
        "state": "Maharashtra",
        "district": "Mumbai City",
        "zone": "WR",
        "division": "Mumbai WR",
        "station_type": "SUBURBAN",
        "corridors": "Western Line",
        "search_aliases": "mahalaxmi, mx, racecourse, dhobi ghat",
        "is_major": False,
        "is_junction": False,
        "platform_count": 3,
        "latitude": 18.9827,
        "longitude": 72.8239,
    },
    {
        "code": "PL",
        "name": "Lower Parel",
        "city": "Mumbai",
        "state": "Maharashtra",
        "district": "Mumbai City",
        "zone": "WR",
        "division": "Mumbai WR",
        "station_type": "SUBURBAN",
        "corridors": "Western Line",
        "search_aliases": "lower parel, pl, currey road west",
        "is_major": False,
        "is_junction": False,
        "platform_count": 3,
        "latitude": 18.9953,
        "longitude": 72.8306,
    },
    {
        "code": "PBHD",
        "name": "Prabhadevi",
        "city": "Mumbai",
        "state": "Maharashtra",
        "district": "Mumbai City",
        "zone": "WR",
        "division": "Mumbai WR",
        "station_type": "SUBURBAN",
        "corridors": "Western Line",
        "search_aliases": "prabhadevi, pbhd, elphinstone road, epr",
        "is_major": False,
        "is_junction": True,
        "platform_count": 2,
        "latitude": 19.0061,
        "longitude": 72.8353,
    },
    {
        "code": "DR",
        "name": "Dadar",
        "city": "Mumbai",
        "state": "Maharashtra",
        "district": "Mumbai City",
        "zone": "CR",
        "division": "Mumbai CR",
        "station_type": "SUBURBAN",
        "corridors": "Central Main, Western Line",
        "search_aliases": "dadar, dadar cr, dadar wr, ddr, dr, bombay dadar",
        "is_major": True,
        "is_junction": True,
        "platform_count": 14,
        "latitude": 19.0178,
        "longitude": 72.8478,
    },
    {
        "code": "MRU",
        "name": "Matunga Road",
        "city": "Mumbai",
        "state": "Maharashtra",
        "district": "Mumbai Suburban",
        "zone": "WR",
        "division": "Mumbai WR",
        "station_type": "SUBURBAN",
        "corridors": "Western Line",
        "search_aliases": "matunga road, mru",
        "is_major": False,
        "is_junction": False,
        "platform_count": 2,
        "latitude": 19.0278,
        "longitude": 72.8456,
    },
    {
        "code": "MM",
        "name": "Mahim Junction",
        "city": "Mumbai",
        "state": "Maharashtra",
        "district": "Mumbai Suburban",
        "zone": "WR",
        "division": "Mumbai WR",
        "station_type": "SUBURBAN",
        "corridors": "Western Line, Harbour Line",
        "search_aliases": "mahim, mm, mahim jn",
        "is_major": False,
        "is_junction": True,
        "platform_count": 6,
        "latitude": 19.0411,
        "longitude": 72.8422,
    },
    {
        "code": "BA",
        "name": "Bandra",
        "city": "Mumbai",
        "state": "Maharashtra",
        "district": "Mumbai Suburban",
        "zone": "WR",
        "division": "Mumbai WR",
        "station_type": "SUBURBAN",
        "corridors": "Western Line, Harbour Line",
        "search_aliases": "bandra, ba, bandra local, bdts, bndr",
        "is_major": True,
        "is_junction": True,
        "platform_count": 7,
        "latitude": 19.0544,
        "longitude": 72.8406,
    },
    {
        "code": "KHAR",
        "name": "Khar Road",
        "city": "Mumbai",
        "state": "Maharashtra",
        "district": "Mumbai Suburban",
        "zone": "WR",
        "division": "Mumbai WR",
        "station_type": "SUBURBAN",
        "corridors": "Western Line",
        "search_aliases": "khar road, khar, khar rd",
        "is_major": False,
        "is_junction": False,
        "platform_count": 4,
        "latitude": 19.0689,
        "longitude": 72.8394,
    },
    {
        "code": "STC",
        "name": "Santacruz",
        "city": "Mumbai",
        "state": "Maharashtra",
        "district": "Mumbai Suburban",
        "zone": "WR",
        "division": "Mumbai WR",
        "station_type": "SUBURBAN",
        "corridors": "Western Line",
        "search_aliases": "santacruz, stc, santa cruz",
        "is_major": False,
        "is_junction": False,
        "platform_count": 4,
        "latitude": 19.0817,
        "longitude": 72.8408,
    },
    {
        "code": "VLP",
        "name": "Vile Parle",
        "city": "Mumbai",
        "state": "Maharashtra",
        "district": "Mumbai Suburban",
        "zone": "WR",
        "division": "Mumbai WR",
        "station_type": "SUBURBAN",
        "corridors": "Western Line",
        "search_aliases": "vile parle, vlp, parle",
        "is_major": False,
        "is_junction": False,
        "platform_count": 5,
        "latitude": 19.0994,
        "longitude": 72.8439,
    },
    {
        "code": "ADH",
        "name": "Andheri",
        "city": "Mumbai",
        "state": "Maharashtra",
        "district": "Mumbai Suburban",
        "zone": "WR",
        "division": "Mumbai WR",
        "station_type": "SUBURBAN",
        "corridors": "Western Line, Harbour Line",
        "search_aliases": "andheri, adh, andheri metro, andheri jn",
        "is_major": True,
        "is_junction": True,
        "platform_count": 9,
        "latitude": 19.1197,
        "longitude": 72.8464,
    },
    {
        "code": "JOS",
        "name": "Jogeshwari",
        "city": "Mumbai",
        "state": "Maharashtra",
        "district": "Mumbai Suburban",
        "zone": "WR",
        "division": "Mumbai WR",
        "station_type": "SUBURBAN",
        "corridors": "Western Line",
        "search_aliases": "jogeshwari, jos",
        "is_major": False,
        "is_junction": False,
        "platform_count": 4,
        "latitude": 19.1361,
        "longitude": 72.8489,
    },
    {
        "code": "RMAR",
        "name": "Ram Mandir",
        "city": "Mumbai",
        "state": "Maharashtra",
        "district": "Mumbai Suburban",
        "zone": "WR",
        "division": "Mumbai WR",
        "station_type": "SUBURBAN",
        "corridors": "Western Line",
        "search_aliases": "ram mandir, rmar, oshiwara",
        "is_major": False,
        "is_junction": False,
        "platform_count": 4,
        "latitude": 19.1511,
        "longitude": 72.8483,
    },
    {
        "code": "GMN",
        "name": "Goregaon",
        "city": "Mumbai",
        "state": "Maharashtra",
        "district": "Mumbai Suburban",
        "zone": "WR",
        "division": "Mumbai WR",
        "station_type": "SUBURBAN",
        "corridors": "Western Line, Harbour Line",
        "search_aliases": "goregaon, gmn, film city",
        "is_major": True,
        "is_junction": True,
        "platform_count": 7,
        "latitude": 19.1644,
        "longitude": 72.8489,
    },
    {
        "code": "MDD",
        "name": "Malad",
        "city": "Mumbai",
        "state": "Maharashtra",
        "district": "Mumbai Suburban",
        "zone": "WR",
        "division": "Mumbai WR",
        "station_type": "SUBURBAN",
        "corridors": "Western Line",
        "search_aliases": "malad, mdd",
        "is_major": False,
        "is_junction": False,
        "platform_count": 4,
        "latitude": 19.1867,
        "longitude": 72.8486,
    },
    {
        "code": "KILE",
        "name": "Kandivali",
        "city": "Mumbai",
        "state": "Maharashtra",
        "district": "Mumbai Suburban",
        "zone": "WR",
        "division": "Mumbai WR",
        "station_type": "SUBURBAN",
        "corridors": "Western Line",
        "search_aliases": "kandivali, kile, kandivli",
        "is_major": False,
        "is_junction": False,
        "platform_count": 4,
        "latitude": 19.2047,
        "longitude": 72.8522,
    },
    {
        "code": "BVI",
        "name": "Borivali",
        "city": "Mumbai",
        "state": "Maharashtra",
        "district": "Mumbai Suburban",
        "zone": "WR",
        "division": "Mumbai WR",
        "station_type": "SUBURBAN",
        "corridors": "Western Line",
        "search_aliases": "borivali, bvi, national park, sgnp",
        "is_major": True,
        "is_junction": True,
        "platform_count": 10,
        "latitude": 19.2297,
        "longitude": 72.8567,
    },
    {
        "code": "DIC",
        "name": "Dahisar",
        "city": "Mumbai",
        "state": "Maharashtra",
        "district": "Mumbai Suburban",
        "zone": "WR",
        "division": "Mumbai WR",
        "station_type": "SUBURBAN",
        "corridors": "Western Line",
        "search_aliases": "dahisar, dic",
        "is_major": False,
        "is_junction": False,
        "platform_count": 4,
        "latitude": 19.2503,
        "longitude": 72.8592,
    },
    {
        "code": "MIRA",
        "name": "Mira Road",
        "city": "Thane",
        "state": "Maharashtra",
        "district": "Thane",
        "zone": "WR",
        "division": "Mumbai WR",
        "station_type": "SUBURBAN",
        "corridors": "Western Line",
        "search_aliases": "mira road, mira, mira-bhayandar",
        "is_major": False,
        "is_junction": False,
        "platform_count": 4,
        "latitude": 19.2814,
        "longitude": 72.8572,
    },
    {
        "code": "BYR",
        "name": "Bhayandar",
        "city": "Thane",
        "state": "Maharashtra",
        "district": "Thane",
        "zone": "WR",
        "division": "Mumbai WR",
        "station_type": "SUBURBAN",
        "corridors": "Western Line",
        "search_aliases": "bhayandar, byr, bhayander",
        "is_major": True,
        "is_junction": False,
        "platform_count": 6,
        "latitude": 19.3017,
        "longitude": 72.8522,
    },
    {
        "code": "NIG",
        "name": "Naigaon",
        "city": "Palghar",
        "state": "Maharashtra",
        "district": "Palghar",
        "zone": "WR",
        "division": "Mumbai WR",
        "station_type": "SUBURBAN",
        "corridors": "Western Line",
        "search_aliases": "naigaon, nig",
        "is_major": False,
        "is_junction": False,
        "platform_count": 2,
        "latitude": 19.3517,
        "longitude": 72.8467,
    },
    {
        "code": "BSR",
        "name": "Vasai Road",
        "city": "Palghar",
        "state": "Maharashtra",
        "district": "Palghar",
        "zone": "WR",
        "division": "Mumbai WR",
        "station_type": "SUBURBAN",
        "corridors": "Western Line, Diva Junction Link",
        "search_aliases": "vasai road, bsr, vasai",
        "is_major": True,
        "is_junction": True,
        "platform_count": 7,
        "latitude": 19.3797,
        "longitude": 72.8397,
    },
    {
        "code": "NSP",
        "name": "Nalasopara",
        "city": "Palghar",
        "state": "Maharashtra",
        "district": "Palghar",
        "zone": "WR",
        "division": "Mumbai WR",
        "station_type": "SUBURBAN",
        "corridors": "Western Line",
        "search_aliases": "nalasopara, nsp, nala sopara",
        "is_major": False,
        "is_junction": False,
        "platform_count": 4,
        "latitude": 19.4181,
        "longitude": 72.8183,
    },
    {
        "code": "VR",
        "name": "Virar",
        "city": "Palghar",
        "state": "Maharashtra",
        "district": "Palghar",
        "zone": "WR",
        "division": "Mumbai WR",
        "station_type": "SUBURBAN",
        "corridors": "Western Line",
        "search_aliases": "virar, vr, virar car shed",
        "is_major": True,
        "is_junction": True,
        "platform_count": 8,
        "latitude": 19.4556,
        "longitude": 72.8089,
    },

    # ==========================================
    # CENTRAL MAIN LINE STATIONS (CSMT -> Kalyan)
    # ==========================================
    {
        "code": "CSMT",
        "name": "Chhatrapati Shivaji Maharaj Terminus",
        "city": "Mumbai",
        "state": "Maharashtra",
        "district": "Mumbai City",
        "zone": "CR",
        "division": "Mumbai CR",
        "station_type": "SUBURBAN",
        "corridors": "Central Main, Harbour Line",
        "search_aliases": "csmt, cst, vt, victoria terminus, bombay cst",
        "is_major": True,
        "is_junction": True,
        "platform_count": 18,
        "latitude": 18.9400,
        "longitude": 72.8353,
    },
    {
        "code": "MSD",
        "name": "Masjid",
        "city": "Mumbai",
        "state": "Maharashtra",
        "district": "Mumbai City",
        "zone": "CR",
        "division": "Mumbai CR",
        "station_type": "SUBURBAN",
        "corridors": "Central Main, Harbour Line",
        "search_aliases": "masjid, msd, masjid bunder",
        "is_major": False,
        "is_junction": False,
        "platform_count": 4,
        "latitude": 18.9519,
        "longitude": 72.8389,
    },
    {
        "code": "SNRD",
        "name": "Sandhurst Road",
        "city": "Mumbai",
        "state": "Maharashtra",
        "district": "Mumbai City",
        "zone": "CR",
        "division": "Mumbai CR",
        "station_type": "SUBURBAN",
        "corridors": "Central Main, Harbour Line",
        "search_aliases": "sandhurst road, snrd",
        "is_major": False,
        "is_junction": True,
        "platform_count": 4,
        "latitude": 18.9614,
        "longitude": 72.8394,
    },
    {
        "code": "BY",
        "name": "Byculla",
        "city": "Mumbai",
        "state": "Maharashtra",
        "district": "Mumbai City",
        "zone": "CR",
        "division": "Mumbai CR",
        "station_type": "SUBURBAN",
        "corridors": "Central Main",
        "search_aliases": "byculla, by, rani baug",
        "is_major": False,
        "is_junction": False,
        "platform_count": 4,
        "latitude": 18.9767,
        "longitude": 72.8336,
    },
    {
        "code": "CHG",
        "name": "Chinchpokli",
        "city": "Mumbai",
        "state": "Maharashtra",
        "district": "Mumbai City",
        "zone": "CR",
        "division": "Mumbai CR",
        "station_type": "SUBURBAN",
        "corridors": "Central Main",
        "search_aliases": "chinchpokli, chg",
        "is_major": False,
        "is_junction": False,
        "platform_count": 2,
        "latitude": 18.9881,
        "longitude": 72.8344,
    },
    {
        "code": "CRD",
        "name": "Currey Road",
        "city": "Mumbai",
        "state": "Maharashtra",
        "district": "Mumbai City",
        "zone": "CR",
        "division": "Mumbai CR",
        "station_type": "SUBURBAN",
        "corridors": "Central Main",
        "search_aliases": "currey road, crd, lalbaug",
        "is_major": False,
        "is_junction": False,
        "platform_count": 2,
        "latitude": 18.9958,
        "longitude": 72.8328,
    },
    {
        "code": "PR",
        "name": "Parel",
        "city": "Mumbai",
        "state": "Maharashtra",
        "district": "Mumbai City",
        "zone": "CR",
        "division": "Mumbai CR",
        "station_type": "SUBURBAN",
        "corridors": "Central Main",
        "search_aliases": "parel, pr, kem hospital",
        "is_major": False,
        "is_junction": True,
        "platform_count": 3,
        "latitude": 19.0069,
        "longitude": 72.8389,
    },
    {
        "code": "MTN",
        "name": "Matunga",
        "city": "Mumbai",
        "state": "Maharashtra",
        "district": "Mumbai Suburban",
        "zone": "CR",
        "division": "Mumbai CR",
        "station_type": "SUBURBAN",
        "corridors": "Central Main",
        "search_aliases": "matunga, mtn, matunga cr",
        "is_major": False,
        "is_junction": False,
        "platform_count": 4,
        "latitude": 19.0272,
        "longitude": 72.8533,
    },
    {
        "code": "SIN",
        "name": "Sion",
        "city": "Mumbai",
        "state": "Maharashtra",
        "district": "Mumbai Suburban",
        "zone": "CR",
        "division": "Mumbai CR",
        "station_type": "SUBURBAN",
        "corridors": "Central Main",
        "search_aliases": "sion, sin, sheev",
        "is_major": False,
        "is_junction": False,
        "platform_count": 4,
        "latitude": 19.0417,
        "longitude": 72.8622,
    },
    {
        "code": "CLA",
        "name": "Kurla",
        "city": "Mumbai",
        "state": "Maharashtra",
        "district": "Mumbai Suburban",
        "zone": "CR",
        "division": "Mumbai CR",
        "station_type": "SUBURBAN",
        "corridors": "Central Main, Harbour Line",
        "search_aliases": "kurla, cla, kurla jn, bkc",
        "is_major": True,
        "is_junction": True,
        "platform_count": 8,
        "latitude": 19.0653,
        "longitude": 72.8792,
    },
    {
        "code": "VVH",
        "name": "Vidyavihar",
        "city": "Mumbai",
        "state": "Maharashtra",
        "district": "Mumbai Suburban",
        "zone": "CR",
        "division": "Mumbai CR",
        "station_type": "SUBURBAN",
        "corridors": "Central Main",
        "search_aliases": "vidyavihar, vvh, somaiya",
        "is_major": False,
        "is_junction": False,
        "platform_count": 4,
        "latitude": 19.0792,
        "longitude": 72.8978,
    },
    {
        "code": "GC",
        "name": "Ghatkopar",
        "city": "Mumbai",
        "state": "Maharashtra",
        "district": "Mumbai Suburban",
        "zone": "CR",
        "division": "Mumbai CR",
        "station_type": "SUBURBAN",
        "corridors": "Central Main",
        "search_aliases": "ghatkopar, gc, ghatkopar metro",
        "is_major": True,
        "is_junction": True,
        "platform_count": 5,
        "latitude": 19.0864,
        "longitude": 72.9081,
    },
    {
        "code": "VK",
        "name": "Vikhroli",
        "city": "Mumbai",
        "state": "Maharashtra",
        "district": "Mumbai Suburban",
        "zone": "CR",
        "division": "Mumbai CR",
        "station_type": "SUBURBAN",
        "corridors": "Central Main",
        "search_aliases": "vikhroli, vk, godrej",
        "is_major": False,
        "is_junction": False,
        "platform_count": 4,
        "latitude": 19.1097,
        "longitude": 72.9286,
    },
    {
        "code": "KJMG",
        "name": "Kanjurmarg",
        "city": "Mumbai",
        "state": "Maharashtra",
        "district": "Mumbai Suburban",
        "zone": "CR",
        "division": "Mumbai CR",
        "station_type": "SUBURBAN",
        "corridors": "Central Main",
        "search_aliases": "kanjurmarg, kjmg, kanjur",
        "is_major": False,
        "is_junction": False,
        "platform_count": 4,
        "latitude": 19.1306,
        "longitude": 72.9367,
    },
    {
        "code": "BND",
        "name": "Bhandup",
        "city": "Mumbai",
        "state": "Maharashtra",
        "district": "Mumbai Suburban",
        "zone": "CR",
        "division": "Mumbai CR",
        "station_type": "SUBURBAN",
        "corridors": "Central Main",
        "search_aliases": "bhandup, bnd",
        "is_major": False,
        "is_junction": False,
        "platform_count": 4,
        "latitude": 19.1469,
        "longitude": 72.9381,
    },
    {
        "code": "NHU",
        "name": "Nahur",
        "city": "Mumbai",
        "state": "Maharashtra",
        "district": "Mumbai Suburban",
        "zone": "CR",
        "division": "Mumbai CR",
        "station_type": "SUBURBAN",
        "corridors": "Central Main",
        "search_aliases": "nahur, nhu",
        "is_major": False,
        "is_junction": False,
        "platform_count": 2,
        "latitude": 19.1583,
        "longitude": 72.9439,
    },
    {
        "code": "MLND",
        "name": "Mulund",
        "city": "Mumbai",
        "state": "Maharashtra",
        "district": "Mumbai Suburban",
        "zone": "CR",
        "division": "Mumbai CR",
        "station_type": "SUBURBAN",
        "corridors": "Central Main",
        "search_aliases": "mulund, mlnd",
        "is_major": False,
        "is_junction": False,
        "platform_count": 4,
        "latitude": 19.1728,
        "longitude": 72.9567,
    },
    {
        "code": "TNA",
        "name": "Thane",
        "city": "Thane",
        "state": "Maharashtra",
        "district": "Thane",
        "zone": "CR",
        "division": "Mumbai CR",
        "station_type": "SUBURBAN",
        "corridors": "Central Main, Trans-Harbour",
        "search_aliases": "thane, tna, thana",
        "is_major": True,
        "is_junction": True,
        "platform_count": 11,
        "latitude": 19.1861,
        "longitude": 72.9758,
    },
    {
        "code": "KLVA",
        "name": "Kalwa",
        "city": "Thane",
        "state": "Maharashtra",
        "district": "Thane",
        "zone": "CR",
        "division": "Mumbai CR",
        "station_type": "SUBURBAN",
        "corridors": "Central Main",
        "search_aliases": "kalwa, klva",
        "is_major": False,
        "is_junction": False,
        "platform_count": 4,
        "latitude": 19.2003,
        "longitude": 72.9942,
    },
    {
        "code": "MBQ",
        "name": "Mumbra",
        "city": "Thane",
        "state": "Maharashtra",
        "district": "Thane",
        "zone": "CR",
        "division": "Mumbai CR",
        "station_type": "SUBURBAN",
        "corridors": "Central Main",
        "search_aliases": "mumbra, mbq",
        "is_major": False,
        "is_junction": False,
        "platform_count": 4,
        "latitude": 19.1906,
        "longitude": 73.0189,
    },
    {
        "code": "DIVA",
        "name": "Diva Junction",
        "city": "Thane",
        "state": "Maharashtra",
        "district": "Thane",
        "zone": "CR",
        "division": "Mumbai CR",
        "station_type": "SUBURBAN",
        "corridors": "Central Main, Vasai-Panvel Link",
        "search_aliases": "diva, diva jn, diva junction",
        "is_major": True,
        "is_junction": True,
        "platform_count": 8,
        "latitude": 19.1889,
        "longitude": 73.0428,
    },
    {
        "code": "KOPR",
        "name": "Kopar",
        "city": "Thane",
        "state": "Maharashtra",
        "district": "Thane",
        "zone": "CR",
        "division": "Mumbai CR",
        "station_type": "SUBURBAN",
        "corridors": "Central Main",
        "search_aliases": "kopar, kopr",
        "is_major": False,
        "is_junction": False,
        "platform_count": 4,
        "latitude": 19.2139,
        "longitude": 73.0781,
    },
    {
        "code": "DI",
        "name": "Dombivli",
        "city": "Thane",
        "state": "Maharashtra",
        "district": "Thane",
        "zone": "CR",
        "division": "Mumbai CR",
        "station_type": "SUBURBAN",
        "corridors": "Central Main",
        "search_aliases": "dombivli, di, dombivali",
        "is_major": True,
        "is_junction": False,
        "platform_count": 5,
        "latitude": 19.2181,
        "longitude": 73.0864,
    },
    {
        "code": "THK",
        "name": "Thakurli",
        "city": "Thane",
        "state": "Maharashtra",
        "district": "Thane",
        "zone": "CR",
        "division": "Mumbai CR",
        "station_type": "SUBURBAN",
        "corridors": "Central Main",
        "search_aliases": "thakurli, thk",
        "is_major": False,
        "is_junction": False,
        "platform_count": 2,
        "latitude": 19.2272,
        "longitude": 73.1039,
    },
    {
        "code": "KYN",
        "name": "Kalyan Junction",
        "city": "Thane",
        "state": "Maharashtra",
        "district": "Thane",
        "zone": "CR",
        "division": "Mumbai CR",
        "station_type": "SUBURBAN",
        "corridors": "Central Main, Kasara Branch, Karjat Branch",
        "search_aliases": "kalyan, kyn, kalyan jn",
        "is_major": True,
        "is_junction": True,
        "platform_count": 8,
        "latitude": 19.2361,
        "longitude": 73.1306,
    },

    # ==========================================
    # CENTRAL EXTENSIONS: KALYAN -> KASARA
    # ==========================================
    {
        "code": "SHAD",
        "name": "Shahad",
        "city": "Thane",
        "state": "Maharashtra",
        "district": "Thane",
        "zone": "CR",
        "division": "Mumbai CR",
        "station_type": "SUBURBAN",
        "corridors": "Central Kasara",
        "search_aliases": "shahad, shad, century rayon",
        "is_major": False,
        "is_junction": False,
        "platform_count": 2,
        "latitude": 19.2558,
        "longitude": 73.1539,
    },
    {
        "code": "ABY",
        "name": "Ambivli",
        "city": "Thane",
        "state": "Maharashtra",
        "district": "Thane",
        "zone": "CR",
        "division": "Mumbai CR",
        "station_type": "SUBURBAN",
        "corridors": "Central Kasara",
        "search_aliases": "ambivli, aby, ambivali",
        "is_major": False,
        "is_junction": False,
        "platform_count": 2,
        "latitude": 19.2778,
        "longitude": 73.1706,
    },
    {
        "code": "TLA",
        "name": "Titwala",
        "city": "Thane",
        "state": "Maharashtra",
        "district": "Thane",
        "zone": "CR",
        "division": "Mumbai CR",
        "station_type": "SUBURBAN",
        "corridors": "Central Kasara",
        "search_aliases": "titwala, tla, titwala ganpati",
        "is_major": True,
        "is_junction": False,
        "platform_count": 3,
        "latitude": 19.3039,
        "longitude": 73.2081,
    },
    {
        "code": "KDV",
        "name": "Khadavli",
        "city": "Thane",
        "state": "Maharashtra",
        "district": "Thane",
        "zone": "CR",
        "division": "Mumbai CR",
        "station_type": "SUBURBAN",
        "corridors": "Central Kasara",
        "search_aliases": "khadavli, kdv",
        "is_major": False,
        "is_junction": False,
        "platform_count": 2,
        "latitude": 19.3667,
        "longitude": 73.2433,
    },
    {
        "code": "VSD",
        "name": "Vasind",
        "city": "Thane",
        "state": "Maharashtra",
        "district": "Thane",
        "zone": "CR",
        "division": "Mumbai CR",
        "station_type": "SUBURBAN",
        "corridors": "Central Kasara",
        "search_aliases": "vasind, vsd",
        "is_major": False,
        "is_junction": False,
        "platform_count": 2,
        "latitude": 19.4139,
        "longitude": 73.2758,
    },
    {
        "code": "ASO",
        "name": "Asangaon",
        "city": "Thane",
        "state": "Maharashtra",
        "district": "Thane",
        "zone": "CR",
        "division": "Mumbai CR",
        "station_type": "SUBURBAN",
        "corridors": "Central Kasara",
        "search_aliases": "asangaon, aso, shahapur",
        "is_major": True,
        "is_junction": False,
        "platform_count": 3,
        "latitude": 19.4447,
        "longitude": 73.3089,
    },
    {
        "code": "ATG",
        "name": "Atgaon",
        "city": "Thane",
        "state": "Maharashtra",
        "district": "Thane",
        "zone": "CR",
        "division": "Mumbai CR",
        "station_type": "SUBURBAN",
        "corridors": "Central Kasara",
        "search_aliases": "atgaon, atg",
        "is_major": False,
        "is_junction": False,
        "platform_count": 2,
        "latitude": 19.5317,
        "longitude": 73.3444,
    },
    {
        "code": "THS",
        "name": "Thansit",
        "city": "Thane",
        "state": "Maharashtra",
        "district": "Thane",
        "zone": "CR",
        "division": "Mumbai CR",
        "station_type": "SUBURBAN",
        "corridors": "Central Kasara",
        "search_aliases": "thansit, ths",
        "is_major": False,
        "is_junction": False,
        "platform_count": 2,
        "latitude": 19.5786,
        "longitude": 73.3769,
    },
    {
        "code": "KE",
        "name": "Khardi",
        "city": "Thane",
        "state": "Maharashtra",
        "district": "Thane",
        "zone": "CR",
        "division": "Mumbai CR",
        "station_type": "SUBURBAN",
        "corridors": "Central Kasara",
        "search_aliases": "khardi, ke",
        "is_major": False,
        "is_junction": False,
        "platform_count": 2,
        "latitude": 19.6056,
        "longitude": 73.4158,
    },
    {
        "code": "KSRA",
        "name": "Kasara",
        "city": "Thane",
        "state": "Maharashtra",
        "district": "Thane",
        "zone": "CR",
        "division": "Mumbai CR",
        "station_type": "SUBURBAN",
        "corridors": "Central Kasara",
        "search_aliases": "kasara, ksra, thal ghat",
        "is_major": True,
        "is_junction": True,
        "platform_count": 4,
        "latitude": 19.6464,
        "longitude": 73.4778,
    },

    # ==========================================
    # CENTRAL EXTENSIONS: KALYAN -> KARJAT
    # ==========================================
    {
        "code": "VLDI",
        "name": "Vitthalwadi",
        "city": "Thane",
        "state": "Maharashtra",
        "district": "Thane",
        "zone": "CR",
        "division": "Mumbai CR",
        "station_type": "SUBURBAN",
        "corridors": "Central Karjat",
        "search_aliases": "vitthalwadi, vldi, vithalwadi",
        "is_major": False,
        "is_junction": False,
        "platform_count": 2,
        "latitude": 19.2292,
        "longitude": 73.1408,
    },
    {
        "code": "ULNR",
        "name": "Ulhasnagar",
        "city": "Thane",
        "state": "Maharashtra",
        "district": "Thane",
        "zone": "CR",
        "division": "Mumbai CR",
        "station_type": "SUBURBAN",
        "corridors": "Central Karjat",
        "search_aliases": "ulhasnagar, ulnr, unr",
        "is_major": False,
        "is_junction": False,
        "platform_count": 2,
        "latitude": 19.2167,
        "longitude": 73.1539,
    },
    {
        "code": "ABH",
        "name": "Ambernath",
        "city": "Thane",
        "state": "Maharashtra",
        "district": "Thane",
        "zone": "CR",
        "division": "Mumbai CR",
        "station_type": "SUBURBAN",
        "corridors": "Central Karjat",
        "search_aliases": "ambernath, abh, ambarnath",
        "is_major": True,
        "is_junction": False,
        "platform_count": 3,
        "latitude": 19.1989,
        "longitude": 73.1906,
    },
    {
        "code": "BUD",
        "name": "Badlapur",
        "city": "Thane",
        "state": "Maharashtra",
        "district": "Thane",
        "zone": "CR",
        "division": "Mumbai CR",
        "station_type": "SUBURBAN",
        "corridors": "Central Karjat",
        "search_aliases": "badlapur, bud",
        "is_major": True,
        "is_junction": False,
        "platform_count": 3,
        "latitude": 19.1561,
        "longitude": 73.2389,
    },
    {
        "code": "VGI",
        "name": "Vangani",
        "city": "Thane",
        "state": "Maharashtra",
        "district": "Thane",
        "zone": "CR",
        "division": "Mumbai CR",
        "station_type": "SUBURBAN",
        "corridors": "Central Karjat",
        "search_aliases": "vangani, vgi",
        "is_major": False,
        "is_junction": False,
        "platform_count": 2,
        "latitude": 19.0911,
        "longitude": 73.2844,
    },
    {
        "code": "SHLU",
        "name": "Shelu",
        "city": "Raigad",
        "state": "Maharashtra",
        "district": "Raigad",
        "zone": "CR",
        "division": "Mumbai CR",
        "station_type": "SUBURBAN",
        "corridors": "Central Karjat",
        "search_aliases": "shelu, shlu, shelu dam",
        "is_major": False,
        "is_junction": False,
        "platform_count": 2,
        "latitude": 19.0639,
        "longitude": 73.3039,
    },
    {
        "code": "NRL",
        "name": "Neral Junction",
        "city": "Raigad",
        "state": "Maharashtra",
        "district": "Raigad",
        "zone": "CR",
        "division": "Mumbai CR",
        "station_type": "SUBURBAN",
        "corridors": "Central Karjat, Matheran Toy Train",
        "search_aliases": "neral, nrl, neral jn, matheran",
        "is_major": True,
        "is_junction": True,
        "platform_count": 4,
        "latitude": 19.0306,
        "longitude": 73.3208,
    },
    {
        "code": "BVS",
        "name": "Bhivpuri Road",
        "city": "Raigad",
        "state": "Maharashtra",
        "district": "Raigad",
        "zone": "CR",
        "division": "Mumbai CR",
        "station_type": "SUBURBAN",
        "corridors": "Central Karjat",
        "search_aliases": "bhivpuri road, bvs, bhivpuri",
        "is_major": False,
        "is_junction": False,
        "platform_count": 2,
        "latitude": 18.9839,
        "longitude": 73.3289,
    },
    {
        "code": "KJT",
        "name": "Karjat Junction",
        "city": "Raigad",
        "state": "Maharashtra",
        "district": "Raigad",
        "zone": "CR",
        "division": "Mumbai CR",
        "station_type": "SUBURBAN",
        "corridors": "Central Karjat, Khopoli Branch, Pune Line",
        "search_aliases": "karjat, kjt, karjat jn",
        "is_major": True,
        "is_junction": True,
        "platform_count": 5,
        "latitude": 18.9136,
        "longitude": 73.3267,
    },

    # ==========================================
    # CENTRAL EXTENSIONS: KARJAT -> KHOPOLI
    # ==========================================
    {
        "code": "PDI",
        "name": "Palasdari",
        "city": "Raigad",
        "state": "Maharashtra",
        "district": "Raigad",
        "zone": "CR",
        "division": "Mumbai CR",
        "station_type": "SUBURBAN",
        "corridors": "Karjat-Khopoli",
        "search_aliases": "palasdari, pdi, palasdhari",
        "is_major": False,
        "is_junction": False,
        "platform_count": 2,
        "latitude": 18.8872,
        "longitude": 73.3364,
    },
    {
        "code": "KLY",
        "name": "Kelavli",
        "city": "Raigad",
        "state": "Maharashtra",
        "district": "Raigad",
        "zone": "CR",
        "division": "Mumbai CR",
        "station_type": "SUBURBAN",
        "corridors": "Karjat-Khopoli",
        "search_aliases": "kelavli, kly",
        "is_major": False,
        "is_junction": False,
        "platform_count": 1,
        "latitude": 18.8542,
        "longitude": 73.3458,
    },
    {
        "code": "DLV",
        "name": "Dolavli",
        "city": "Raigad",
        "state": "Maharashtra",
        "district": "Raigad",
        "zone": "CR",
        "division": "Mumbai CR",
        "station_type": "SUBURBAN",
        "corridors": "Karjat-Khopoli",
        "search_aliases": "dolavli, dlv",
        "is_major": False,
        "is_junction": False,
        "platform_count": 1,
        "latitude": 18.8286,
        "longitude": 73.3503,
    },
    {
        "code": "LWJ",
        "name": "Lowjee",
        "city": "Raigad",
        "state": "Maharashtra",
        "district": "Raigad",
        "zone": "CR",
        "division": "Mumbai CR",
        "station_type": "SUBURBAN",
        "corridors": "Karjat-Khopoli",
        "search_aliases": "lowjee, lwj",
        "is_major": False,
        "is_junction": False,
        "platform_count": 1,
        "latitude": 18.8078,
        "longitude": 73.3475,
    },
    {
        "code": "KHPI",
        "name": "Khopoli",
        "city": "Raigad",
        "state": "Maharashtra",
        "district": "Raigad",
        "zone": "CR",
        "division": "Mumbai CR",
        "station_type": "SUBURBAN",
        "corridors": "Karjat-Khopoli",
        "search_aliases": "khopoli, khpi, imagica",
        "is_major": True,
        "is_junction": False,
        "platform_count": 2,
        "latitude": 18.7892,
        "longitude": 73.3444,
    },

    # ==========================================
    # HARBOUR LINE STATIONS (CSMT -> Panvel)
    # ==========================================
    {
        "code": "DKRD",
        "name": "Dockyard Road",
        "city": "Mumbai",
        "state": "Maharashtra",
        "district": "Mumbai City",
        "zone": "CR",
        "division": "Mumbai CR",
        "station_type": "SUBURBAN",
        "corridors": "Harbour Line",
        "search_aliases": "dockyard road, dkrd, mazgaon",
        "is_major": False,
        "is_junction": False,
        "platform_count": 2,
        "latitude": 18.9664,
        "longitude": 72.8428,
    },
    {
        "code": "RRD",
        "name": "Reay Road",
        "city": "Mumbai",
        "state": "Maharashtra",
        "district": "Mumbai City",
        "zone": "CR",
        "division": "Mumbai CR",
        "station_type": "SUBURBAN",
        "corridors": "Harbour Line",
        "search_aliases": "reay road, rrd",
        "is_major": False,
        "is_junction": False,
        "platform_count": 2,
        "latitude": 18.9744,
        "longitude": 72.8456,
    },
    {
        "code": "CTGN",
        "name": "Cotton Green",
        "city": "Mumbai",
        "state": "Maharashtra",
        "district": "Mumbai City",
        "zone": "CR",
        "division": "Mumbai CR",
        "station_type": "SUBURBAN",
        "corridors": "Harbour Line",
        "search_aliases": "cotton green, ctgn",
        "is_major": False,
        "is_junction": False,
        "platform_count": 2,
        "latitude": 18.9861,
        "longitude": 72.8489,
    },
    {
        "code": "SVE",
        "name": "Sewri",
        "city": "Mumbai",
        "state": "Maharashtra",
        "district": "Mumbai City",
        "zone": "CR",
        "division": "Mumbai CR",
        "station_type": "SUBURBAN",
        "corridors": "Harbour Line",
        "search_aliases": "sewri, sve, flamingos, trans harbour link",
        "is_major": False,
        "is_junction": False,
        "platform_count": 2,
        "latitude": 18.9989,
        "longitude": 72.8539,
    },
    {
        "code": "VDLR",
        "name": "Wadala Road",
        "city": "Mumbai",
        "state": "Maharashtra",
        "district": "Mumbai City",
        "zone": "CR",
        "division": "Mumbai CR",
        "station_type": "SUBURBAN",
        "corridors": "Harbour Line, Western Harbour Link",
        "search_aliases": "wadala road, vdlr, wadala, wadala jn",
        "is_major": True,
        "is_junction": True,
        "platform_count": 4,
        "latitude": 19.0169,
        "longitude": 72.8589,
    },
    {
        "code": "GTBN",
        "name": "Guru Tegh Bahadur Nagar",
        "city": "Mumbai",
        "state": "Maharashtra",
        "district": "Mumbai Suburban",
        "zone": "CR",
        "division": "Mumbai CR",
        "station_type": "SUBURBAN",
        "corridors": "Harbour Line",
        "search_aliases": "gtb nagar, gtbn, guru tegh bahadur nagar, koliwada",
        "is_major": False,
        "is_junction": False,
        "platform_count": 2,
        "latitude": 19.0356,
        "longitude": 72.8681,
    },
    {
        "code": "CHF",
        "name": "Chunabhatti",
        "city": "Mumbai",
        "state": "Maharashtra",
        "district": "Mumbai Suburban",
        "zone": "CR",
        "division": "Mumbai CR",
        "station_type": "SUBURBAN",
        "corridors": "Harbour Line",
        "search_aliases": "chunabhatti, chf",
        "is_major": False,
        "is_junction": False,
        "platform_count": 2,
        "latitude": 19.0494,
        "longitude": 72.8731,
    },
    {
        "code": "TKNG",
        "name": "Tilak Nagar",
        "city": "Mumbai",
        "state": "Maharashtra",
        "district": "Mumbai Suburban",
        "zone": "CR",
        "division": "Mumbai CR",
        "station_type": "SUBURBAN",
        "corridors": "Harbour Line",
        "search_aliases": "tilak nagar, tkng, ltt local",
        "is_major": False,
        "is_junction": False,
        "platform_count": 2,
        "latitude": 19.0681,
        "longitude": 72.8942,
    },
    {
        "code": "CMBR",
        "name": "Chembur",
        "city": "Mumbai",
        "state": "Maharashtra",
        "district": "Mumbai Suburban",
        "zone": "CR",
        "division": "Mumbai CR",
        "station_type": "SUBURBAN",
        "corridors": "Harbour Line",
        "search_aliases": "chembur, cmbr, chembur monorail",
        "is_major": False,
        "is_junction": False,
        "platform_count": 2,
        "latitude": 19.0622,
        "longitude": 72.9006,
    },
    {
        "code": "GV",
        "name": "Govandi",
        "city": "Mumbai",
        "state": "Maharashtra",
        "district": "Mumbai Suburban",
        "zone": "CR",
        "division": "Mumbai CR",
        "station_type": "SUBURBAN",
        "corridors": "Harbour Line",
        "search_aliases": "govandi, gv",
        "is_major": False,
        "is_junction": False,
        "platform_count": 2,
        "latitude": 19.0558,
        "longitude": 72.9156,
    },
    {
        "code": "MNKD",
        "name": "Mankhurd",
        "city": "Mumbai",
        "state": "Maharashtra",
        "district": "Mumbai Suburban",
        "zone": "CR",
        "division": "Mumbai CR",
        "station_type": "SUBURBAN",
        "corridors": "Harbour Line",
        "search_aliases": "mankhurd, mnkd",
        "is_major": False,
        "is_junction": False,
        "platform_count": 3,
        "latitude": 19.0528,
        "longitude": 72.9328,
    },
    {
        "code": "VSH",
        "name": "Vashi",
        "city": "Navi Mumbai",
        "state": "Maharashtra",
        "district": "Thane",
        "zone": "CR",
        "division": "Mumbai CR",
        "station_type": "SUBURBAN",
        "corridors": "Harbour Line, Trans-Harbour",
        "search_aliases": "vashi, vsh, navi mumbai vashi",
        "is_major": True,
        "is_junction": True,
        "platform_count": 4,
        "latitude": 19.0644,
        "longitude": 72.9989,
    },
    {
        "code": "SNCR",
        "name": "Sanpada",
        "city": "Navi Mumbai",
        "state": "Maharashtra",
        "district": "Thane",
        "zone": "CR",
        "division": "Mumbai CR",
        "station_type": "SUBURBAN",
        "corridors": "Harbour Line, Trans-Harbour",
        "search_aliases": "sanpada, sncr, sanpada car shed",
        "is_major": False,
        "is_junction": True,
        "platform_count": 4,
        "latitude": 19.0664,
        "longitude": 73.0089,
    },
    {
        "code": "JNJ",
        "name": "Juinagar",
        "city": "Navi Mumbai",
        "state": "Maharashtra",
        "district": "Thane",
        "zone": "CR",
        "division": "Mumbai CR",
        "station_type": "SUBURBAN",
        "corridors": "Harbour Line, Trans-Harbour",
        "search_aliases": "juinagar, jnj",
        "is_major": False,
        "is_junction": True,
        "platform_count": 4,
        "latitude": 19.0578,
        "longitude": 73.0175,
    },
    {
        "code": "NEU",
        "name": "Nerul",
        "city": "Navi Mumbai",
        "state": "Maharashtra",
        "district": "Thane",
        "zone": "CR",
        "division": "Mumbai CR",
        "station_type": "SUBURBAN",
        "corridors": "Harbour Line, Trans-Harbour, Nerul-Uran Corridor",
        "search_aliases": "nerul, neu, dy patil, nerul jn",
        "is_major": True,
        "is_junction": True,
        "platform_count": 6,
        "latitude": 19.0336,
        "longitude": 73.0189,
    },
    {
        "code": "SWDV",
        "name": "Seawoods-Darave",
        "city": "Navi Mumbai",
        "state": "Maharashtra",
        "district": "Thane",
        "zone": "CR",
        "division": "Mumbai CR",
        "station_type": "SUBURBAN",
        "corridors": "Harbour Line, Nerul-Uran Corridor",
        "search_aliases": "seawoods, swdv, seawoods-darave, swdk, grand central",
        "is_major": True,
        "is_junction": True,
        "platform_count": 4,
        "latitude": 19.0206,
        "longitude": 73.0197,
    },
    {
        "code": "BEPR",
        "name": "CBD Belapur",
        "city": "Navi Mumbai",
        "state": "Maharashtra",
        "district": "Thane",
        "zone": "CR",
        "division": "Mumbai CR",
        "station_type": "SUBURBAN",
        "corridors": "Harbour Line, Nerul-Uran Corridor",
        "search_aliases": "belapur, bepr, cbd belapur, c.b.d belapur",
        "is_major": True,
        "is_junction": True,
        "platform_count": 4,
        "latitude": 19.0192,
        "longitude": 73.0392,
    },
    {
        "code": "KHAG",
        "name": "Kharghar",
        "city": "Navi Mumbai",
        "state": "Maharashtra",
        "district": "Raigad",
        "zone": "CR",
        "division": "Mumbai CR",
        "station_type": "SUBURBAN",
        "corridors": "Harbour Line",
        "search_aliases": "kharghar, khag, central park kharghar",
        "is_major": False,
        "is_junction": False,
        "platform_count": 4,
        "latitude": 19.0278,
        "longitude": 73.0647,
    },
    {
        "code": "MANR",
        "name": "Mansarovar",
        "city": "Navi Mumbai",
        "state": "Maharashtra",
        "district": "Raigad",
        "zone": "CR",
        "division": "Mumbai CR",
        "station_type": "SUBURBAN",
        "corridors": "Harbour Line",
        "search_aliases": "mansarovar, manr, kamothe",
        "is_major": False,
        "is_junction": False,
        "platform_count": 2,
        "latitude": 19.0178,
        "longitude": 73.0847,
    },
    {
        "code": "KNDS",
        "name": "Khandeshwar",
        "city": "Navi Mumbai",
        "state": "Maharashtra",
        "district": "Raigad",
        "zone": "CR",
        "division": "Mumbai CR",
        "station_type": "SUBURBAN",
        "corridors": "Harbour Line",
        "search_aliases": "khandeshwar, knds",
        "is_major": False,
        "is_junction": False,
        "platform_count": 2,
        "latitude": 19.0069,
        "longitude": 73.1006,
    },
    {
        "code": "PNVL",
        "name": "Panvel Junction",
        "city": "Navi Mumbai",
        "state": "Maharashtra",
        "district": "Raigad",
        "zone": "CR",
        "division": "Mumbai CR",
        "station_type": "SUBURBAN",
        "corridors": "Harbour Line, Trans-Harbour, Konkan Line",
        "search_aliases": "panvel, pnvl, panvel jn",
        "is_major": True,
        "is_junction": True,
        "platform_count": 7,
        "latitude": 18.9894,
        "longitude": 73.1219,
    },

    # ==========================================
    # TRANS-HARBOUR LINE SPECIFIC STATIONS
    # ==========================================
    {
        "code": "DIGHA",
        "name": "Digha Gaon",
        "city": "Thane",
        "state": "Maharashtra",
        "district": "Thane",
        "zone": "CR",
        "division": "Mumbai CR",
        "station_type": "SUBURBAN",
        "corridors": "Trans-Harbour",
        "search_aliases": "digha, digha gaon, digha railway station",
        "is_major": False,
        "is_junction": False,
        "platform_count": 2,
        "latitude": 19.1678,
        "longitude": 72.9867,
    },
    {
        "code": "AIRL",
        "name": "Airoli",
        "city": "Navi Mumbai",
        "state": "Maharashtra",
        "district": "Thane",
        "zone": "CR",
        "division": "Mumbai CR",
        "station_type": "SUBURBAN",
        "corridors": "Trans-Harbour",
        "search_aliases": "airoli, airl, mindspace",
        "is_major": False,
        "is_junction": False,
        "platform_count": 2,
        "latitude": 19.1558,
        "longitude": 72.9989,
    },
    {
        "code": "RABE",
        "name": "Rabale",
        "city": "Navi Mumbai",
        "state": "Maharashtra",
        "district": "Thane",
        "zone": "CR",
        "division": "Mumbai CR",
        "station_type": "SUBURBAN",
        "corridors": "Trans-Harbour",
        "search_aliases": "rabale, rabe, midc rabale",
        "is_major": False,
        "is_junction": False,
        "platform_count": 2,
        "latitude": 19.1389,
        "longitude": 73.0078,
    },
    {
        "code": "GNSL",
        "name": "Ghansoli",
        "city": "Navi Mumbai",
        "state": "Maharashtra",
        "district": "Thane",
        "zone": "CR",
        "division": "Mumbai CR",
        "station_type": "SUBURBAN",
        "corridors": "Trans-Harbour",
        "search_aliases": "ghansoli, gnsl, reliance corporate park",
        "is_major": False,
        "is_junction": False,
        "platform_count": 2,
        "latitude": 19.1219,
        "longitude": 73.0108,
    },
    {
        "code": "KPHN",
        "name": "Kopar Khairane",
        "city": "Navi Mumbai",
        "state": "Maharashtra",
        "district": "Thane",
        "zone": "CR",
        "division": "Mumbai CR",
        "station_type": "SUBURBAN",
        "corridors": "Trans-Harbour",
        "search_aliases": "kopar khairane, kphn, koparkhairane",
        "is_major": False,
        "is_junction": False,
        "platform_count": 2,
        "latitude": 19.1039,
        "longitude": 73.0139,
    },
    {
        "code": "TUH",
        "name": "Turbhe",
        "city": "Navi Mumbai",
        "state": "Maharashtra",
        "district": "Thane",
        "zone": "CR",
        "division": "Mumbai CR",
        "station_type": "SUBURBAN",
        "corridors": "Trans-Harbour",
        "search_aliases": "turbhe, tuh, apmc market",
        "is_major": True,
        "is_junction": True,
        "platform_count": 4,
        "latitude": 19.0789,
        "longitude": 73.0189,
    },

    # ==========================================
    # NERUL / BELAPUR -> URAN CORRIDOR (Phase 2)
    # ==========================================
    {
        "code": "TRGR",
        "name": "Targhar",
        "city": "Navi Mumbai",
        "state": "Maharashtra",
        "district": "Raigad",
        "zone": "CR",
        "division": "Mumbai CR",
        "station_type": "SUBURBAN",
        "corridors": "Nerul-Uran Corridor",
        "search_aliases": "targhar, trgr, navi mumbai airport",
        "is_major": False,
        "is_junction": False,
        "platform_count": 2,
        "latitude": 18.9953,
        "longitude": 73.0306,
    },
    {
        "code": "BMDR",
        "name": "Bamandongri",
        "city": "Navi Mumbai",
        "state": "Maharashtra",
        "district": "Raigad",
        "zone": "CR",
        "division": "Mumbai CR",
        "station_type": "SUBURBAN",
        "corridors": "Nerul-Uran Corridor",
        "search_aliases": "bamandongri, bmdr, ulwe bamandongri",
        "is_major": False,
        "is_junction": False,
        "platform_count": 2,
        "latitude": 18.9772,
        "longitude": 73.0239,
    },
    {
        "code": "KARP",
        "name": "Kharkopar",
        "city": "Navi Mumbai",
        "state": "Maharashtra",
        "district": "Raigad",
        "zone": "CR",
        "division": "Mumbai CR",
        "station_type": "SUBURBAN",
        "corridors": "Nerul-Uran Corridor",
        "search_aliases": "kharkopar, karp, khkpr, ulwe",
        "is_major": True,
        "is_junction": False,
        "platform_count": 2,
        "latitude": 18.9608,
        "longitude": 73.0175,
    },
    {
        "code": "GAVN",
        "name": "Gavhan",
        "city": "Navi Mumbai",
        "state": "Maharashtra",
        "district": "Raigad",
        "zone": "CR",
        "division": "Mumbai CR",
        "station_type": "SUBURBAN",
        "corridors": "Nerul-Uran Corridor",
        "search_aliases": "gavhan, gavan, gavn",
        "is_major": False,
        "is_junction": False,
        "platform_count": 2,
        "latitude": 18.9389,
        "longitude": 73.0108,
    },
    {
        "code": "SEMK",
        "name": "Ranjanpada",
        "city": "Navi Mumbai",
        "state": "Maharashtra",
        "district": "Raigad",
        "zone": "CR",
        "division": "Mumbai CR",
        "station_type": "SUBURBAN",
        "corridors": "Nerul-Uran Corridor",
        "search_aliases": "ranjanpada, semk, shematikhar, rjnpd, rmnd",
        "is_major": False,
        "is_junction": False,
        "platform_count": 2,
        "latitude": 18.9214,
        "longitude": 73.0039,
    },
    {
        "code": "NESA",
        "name": "Nhava Sheva",
        "city": "Navi Mumbai",
        "state": "Maharashtra",
        "district": "Raigad",
        "zone": "CR",
        "division": "Mumbai CR",
        "station_type": "SUBURBAN",
        "corridors": "Nerul-Uran Corridor",
        "search_aliases": "nhava sheva, nesa, jnpt, nshv",
        "is_major": True,
        "is_junction": False,
        "platform_count": 2,
        "latitude": 18.9036,
        "longitude": 72.9917,
    },
    {
        "code": "DRGI",
        "name": "Dronagiri",
        "city": "Navi Mumbai",
        "state": "Maharashtra",
        "district": "Raigad",
        "zone": "CR",
        "division": "Mumbai CR",
        "station_type": "SUBURBAN",
        "corridors": "Nerul-Uran Corridor",
        "search_aliases": "dronagiri, drgi, dngr, dronagiri fort",
        "is_major": False,
        "is_junction": False,
        "platform_count": 2,
        "latitude": 18.8872,
        "longitude": 72.9739,
    },
    {
        "code": "URAN",
        "name": "Uran",
        "city": "Navi Mumbai",
        "state": "Maharashtra",
        "district": "Raigad",
        "zone": "CR",
        "division": "Mumbai CR",
        "station_type": "SUBURBAN",
        "corridors": "Nerul-Uran Corridor",
        "search_aliases": "uran, uran city, port line, unr local",
        "is_major": True,
        "is_junction": False,
        "platform_count": 2,
        "latitude": 18.8789,
        "longitude": 72.9439,
    },
]

# Corridor operational sequences
WESTERN_LINE_SEQUENCE = [
    "CCG", "MEL", "CYR", "GTR", "MMCT", "MX", "PL", "PBHD", "DR", "MRU",
    "MM", "BA", "KHAR", "STC", "VLP", "ADH", "JOS", "RMAR", "GMN", "MDD",
    "KILE", "BVI", "DIC", "MIRA", "BYR", "NIG", "BSR", "NSP", "VR"
]

CENTRAL_MAIN_SEQUENCE = [
    "CSMT", "MSD", "SNRD", "BY", "CHG", "CRD", "PR", "DR", "MTN", "SIN",
    "CLA", "VVH", "GC", "VK", "KJMG", "BND", "NHU", "MLND", "TNA", "KLVA",
    "MBQ", "DIVA", "KOPR", "DI", "THK", "KYN"
]

CENTRAL_KASARA_SEQUENCE = [
    "KYN", "SHAD", "ABY", "TLA", "KDV", "VSD", "ASO", "ATG", "THS", "KE", "KSRA"
]

CENTRAL_KARJAT_SEQUENCE = [
    "KYN", "VLDI", "ULNR", "ABH", "BUD", "VGI", "SHLU", "NRL", "BVS", "KJT"
]

KARJAT_KHOPOLI_SEQUENCE = [
    "KJT", "PDI", "KLY", "DLV", "LWJ", "KHPI"
]

HARBOUR_LINE_SEQUENCE = [
    "CSMT", "MSD", "SNRD", "DKRD", "RRD", "CTGN", "SVE", "VDLR", "GTBN", "CHF",
    "CLA", "TKNG", "CMBR", "GV", "MNKD", "VSH", "SNCR", "JNJ", "NEU", "SWDV",
    "BEPR", "KHAG", "MANR", "KNDS", "PNVL"
]

TRANS_HARBOUR_VASHI_SEQUENCE = [
    "TNA", "DIGHA", "AIRL", "RABE", "GNSL", "KPHN", "TUH", "SNCR", "VSH"
]

TRANS_HARBOUR_NERUL_PANVEL_SEQUENCE = [
    "TNA", "DIGHA", "AIRL", "RABE", "GNSL", "KPHN", "TUH", "JNJ", "NEU", "SWDV",
    "BEPR", "KHAG", "MANR", "KNDS", "PNVL"
]

NERUL_URAN_SEQUENCE = [
    "NEU", "SWDV", "TRGR", "BMDR", "KARP", "GAVN", "SEMK", "NESA", "DRGI", "URAN"
]

BELAPUR_URAN_SEQUENCE = [
    "BEPR", "TRGR", "BMDR", "KARP", "GAVN", "SEMK", "NESA", "DRGI", "URAN"
]

def make_suburban_train_spec(
    number: str,
    name: str,
    sequence: list,
    start_time: str = "07:00",
    minutes_per_stop: int = 3,
    train_type: str = "Suburban EMU",
    classes: str = "2S,CC"
):
    from datetime import datetime, timedelta
    base_t = datetime.strptime(start_time, "%H:%M")
    stops = []
    total_stops = len(sequence)
    for i, code in enumerate(sequence):
        stop_arr_t = base_t + timedelta(minutes=i * minutes_per_stop)
        stop_dep_t = stop_arr_t + timedelta(minutes=1) if i < total_stops - 1 else stop_arr_t
        arr_str = stop_arr_t.strftime("%H:%M")
        dep_str = stop_dep_t.strftime("%H:%M")
        dist = i * 3
        # (station_code, sequence_idx, arr_time, dep_time, halt_mins, day_number, distance_km)
        halt = 1 if (0 < i < total_stops - 1) else 0
        stops.append((code, i, arr_str, dep_str, halt, 1, dist))
    
    first_dep = stops[0][3]
    last_arr = stops[-1][2]
    dur = round((total_stops * minutes_per_stop) / 60.0, 2)
    return (
        number,
        name,
        train_type,
        sequence[0],
        sequence[-1],
        first_dep,
        last_arr,
        dur,
        "1,2,3,4,5,6,7",
        classes,
        stops
    )

def get_mumbai_suburban_trains_spec():
    """Returns train specifications for all Mumbai Suburban corridors in both directions."""
    return [
        # 1. Western Line (Churchgate <-> Virar)
        make_suburban_train_spec("90001", "Churchgate - Virar Slow Local", WESTERN_LINE_SEQUENCE, "06:30", 3),
        make_suburban_train_spec("90002", "Virar - Churchgate Slow Local", list(reversed(WESTERN_LINE_SEQUENCE)), "08:15", 3),
        
        # 2. Central Main Line (CSMT <-> Kalyan)
        make_suburban_train_spec("97001", "CSMT - Kalyan Slow Local", CENTRAL_MAIN_SEQUENCE, "06:45", 3),
        make_suburban_train_spec("97002", "Kalyan - CSMT Slow Local", list(reversed(CENTRAL_MAIN_SEQUENCE)), "08:20", 3),

        # 3. Central Line: Kalyan <-> Kasara
        make_suburban_train_spec("97501", "Kalyan - Kasara Local", CENTRAL_KASARA_SEQUENCE, "07:15", 4),
        make_suburban_train_spec("97502", "Kasara - Kalyan Local", list(reversed(CENTRAL_KASARA_SEQUENCE)), "08:30", 4),

        # 4. Central Line: Kalyan <-> Karjat
        make_suburban_train_spec("97601", "Kalyan - Karjat Local", CENTRAL_KARJAT_SEQUENCE, "07:30", 4),
        make_suburban_train_spec("97602", "Karjat - Kalyan Local", list(reversed(CENTRAL_KARJAT_SEQUENCE)), "08:45", 4),

        # 5. Central Line: Karjat <-> Khopoli Shuttle
        make_suburban_train_spec("97701", "Karjat - Khopoli Shuttle", KARJAT_KHOPOLI_SEQUENCE, "08:00", 5),
        make_suburban_train_spec("97702", "Khopoli - Karjat Shuttle", list(reversed(KARJAT_KHOPOLI_SEQUENCE)), "09:00", 5),

        # 6. Harbour Line (CSMT <-> Panvel)
        make_suburban_train_spec("98001", "CSMT - Panvel Slow Local", HARBOUR_LINE_SEQUENCE, "06:15", 3),
        make_suburban_train_spec("98002", "Panvel - CSMT Slow Local", list(reversed(HARBOUR_LINE_SEQUENCE)), "07:50", 3),

        # 7. Trans-Harbour Line: Thane <-> Vashi
        make_suburban_train_spec("99001", "Thane - Vashi Local", TRANS_HARBOUR_VASHI_SEQUENCE, "07:10", 3),
        make_suburban_train_spec("99002", "Vashi - Thane Local", list(reversed(TRANS_HARBOUR_VASHI_SEQUENCE)), "08:05", 3),

        # 8. Trans-Harbour Line: Thane <-> Panvel (via Nerul)
        make_suburban_train_spec("99101", "Thane - Panvel Local", TRANS_HARBOUR_NERUL_PANVEL_SEQUENCE, "06:50", 3),
        make_suburban_train_spec("99102", "Panvel - Thane Local", list(reversed(TRANS_HARBOUR_NERUL_PANVEL_SEQUENCE)), "08:10", 3),

        # 9. Nerul - Uran Corridor (Port Line Phase 2)
        make_suburban_train_spec("99601", "Nerul - Uran Local", NERUL_URAN_SEQUENCE, "07:05", 3),
        make_suburban_train_spec("99602", "Uran - Nerul Local", list(reversed(NERUL_URAN_SEQUENCE)), "08:15", 3),

        # 10. CBD Belapur - Uran Corridor
        make_suburban_train_spec("99701", "CBD Belapur - Uran Local", BELAPUR_URAN_SEQUENCE, "07:25", 3),
        make_suburban_train_spec("99702", "Uran - CBD Belapur Local", list(reversed(BELAPUR_URAN_SEQUENCE)), "08:35", 3),
    ]

