"""
Comprehensive master station database for Indian Railways.
Contains 250+ major junction, terminal, suburban and divisional stations across India.
Includes search aliases, divisions, zones, and coordinates for quick and accurate routing.
"""

STATIONS_MASTER = [
    # --- MUMBAI METROPOLITAN & KONKAN ---
    {
        "code": "MMCT",
        "name": "Mumbai Central",
        "city": "Mumbai",
        "state": "Maharashtra",
        "zone": "WR",
        "division": "Mumbai",
        "search_aliases": "bct, mumbai central, bombay central, bombay, mmct",
        "is_major": True,
        "is_junction": False,
        "platform_count": 8,
        "latitude": 18.9696,
        "longitude": 72.8193,
    },
    {
        "code": "BCT",
        "name": "Mumbai Central (Main)",
        "city": "Mumbai",
        "state": "Maharashtra",
        "zone": "WR",
        "division": "Mumbai",
        "search_aliases": "mmct, mumbai central, bombay central, bct",
        "is_major": True,
        "is_junction": False,
        "platform_count": 8,
        "latitude": 18.9696,
        "longitude": 72.8193,
    },
    {
        "code": "CSMT",
        "name": "Chhatrapati Shivaji Maharaj Terminus",
        "city": "Mumbai",
        "state": "Maharashtra",
        "zone": "CR",
        "division": "Mumbai",
        "search_aliases": "cst, vt, victoria terminus, bombay vt, bombay cst, bombay, csmt",
        "is_major": True,
        "is_junction": True,
        "platform_count": 18,
        "latitude": 18.9400,
        "longitude": 72.8353,
    },
    {
        "code": "DR",
        "name": "Dadar Central",
        "city": "Mumbai",
        "state": "Maharashtra",
        "zone": "CR",
        "division": "Mumbai",
        "search_aliases": "dadar, dadar cr, dadar wr, ddr, bombay dadar",
        "is_major": True,
        "is_junction": True,
        "platform_count": 8,
        "latitude": 19.0178,
        "longitude": 72.8478,
    },
    {
        "code": "TNA",
        "name": "Thane",
        "city": "Thane",
        "state": "Maharashtra",
        "zone": "CR",
        "division": "Mumbai",
        "search_aliases": "thana, thane junction, tna, mumbai thane",
        "is_major": True,
        "is_junction": True,
        "platform_count": 10,
        "latitude": 19.1860,
        "longitude": 72.9759,
    },
    {
        "code": "KYN",
        "name": "Kalyan Junction",
        "city": "Kalyan",
        "state": "Maharashtra",
        "zone": "CR",
        "division": "Mumbai",
        "search_aliases": "kalyan, kalyan jn, kyn, mumbai kalyan",
        "is_major": True,
        "is_junction": True,
        "platform_count": 8,
        "latitude": 19.2354,
        "longitude": 73.1299,
    },
    {
        "code": "BDTS",
        "name": "Mumbai Bandra Terminus",
        "city": "Mumbai",
        "state": "Maharashtra",
        "zone": "WR",
        "division": "Mumbai",
        "search_aliases": "bandra terminus, bandra, bdts, bombay bandra",
        "is_major": True,
        "is_junction": False,
        "platform_count": 7,
        "latitude": 19.0628,
        "longitude": 72.8417,
    },
    {
        "code": "LTT",
        "name": "Lokmanya Tilak Terminus",
        "city": "Mumbai",
        "state": "Maharashtra",
        "zone": "CR",
        "division": "Mumbai",
        "search_aliases": "kurla terminus, kurla, ltt, lokmanya tilak",
        "is_major": True,
        "is_junction": False,
        "platform_count": 5,
        "latitude": 19.0699,
        "longitude": 72.8913,
    },
    {
        "code": "BVI",
        "name": "Borivali",
        "city": "Mumbai",
        "state": "Maharashtra",
        "zone": "WR",
        "division": "Mumbai",
        "search_aliases": "borivli, borivali, bvi",
        "is_major": True,
        "is_junction": False,
        "platform_count": 10,
        "latitude": 19.2294,
        "longitude": 72.8573,
    },
    {
        "code": "PNVL",
        "name": "Panvel Junction",
        "city": "Navi Mumbai",
        "state": "Maharashtra",
        "zone": "CR",
        "division": "Mumbai",
        "search_aliases": "panvel, navi mumbai, pnvl",
        "is_major": True,
        "is_junction": True,
        "platform_count": 7,
        "latitude": 18.9894,
        "longitude": 73.1216,
    },
    {
        "code": "BSR",
        "name": "Vasai Road",
        "city": "Vasai",
        "state": "Maharashtra",
        "zone": "WR",
        "division": "Mumbai",
        "search_aliases": "vasai, bassean, bsr",
        "is_major": True,
        "is_junction": True,
        "platform_count": 7,
        "latitude": 19.3828,
        "longitude": 72.8322,
    },
    {
        "code": "PLG",
        "name": "Palghar",
        "city": "Palghar",
        "state": "Maharashtra",
        "zone": "WR",
        "division": "Mumbai",
        "search_aliases": "palghar, plg",
        "is_major": False,
        "is_junction": False,
        "platform_count": 3,
        "latitude": 19.6967,
        "longitude": 72.7655,
    },
    {
        "code": "RN",
        "name": "Ratnagiri",
        "city": "Ratnagiri",
        "state": "Maharashtra",
        "zone": "KR",
        "division": "Ratnagiri",
        "search_aliases": "ratnagiri, konkan, rn",
        "is_major": True,
        "is_junction": False,
        "platform_count": 3,
        "latitude": 16.9859,
        "longitude": 73.3371,
    },
    {
        "code": "MAO",
        "name": "Madgaon Junction",
        "city": "Margao",
        "state": "Goa",
        "zone": "KR",
        "division": "Karwar",
        "search_aliases": "goa, margao, madgaon, konkan goa, mao",
        "is_major": True,
        "is_junction": True,
        "platform_count": 4,
        "latitude": 15.2736,
        "longitude": 73.9789,
    },
    {
        "code": "VSG",
        "name": "Vasco da Gama",
        "city": "Vasco",
        "state": "Goa",
        "zone": "SWR",
        "division": "Hubballi",
        "search_aliases": "vasco, goa vasco, vsg",
        "is_major": True,
        "is_junction": False,
        "platform_count": 3,
        "latitude": 15.3982,
        "longitude": 73.8122,
    },
    {
        "code": "KAWR",
        "name": "Karwar",
        "city": "Karwar",
        "state": "Karnataka",
        "zone": "KR",
        "division": "Karwar",
        "search_aliases": "karwar, kawr",
        "is_major": False,
        "is_junction": False,
        "platform_count": 2,
        "latitude": 14.8211,
        "longitude": 74.1528,
    },

    # --- PUNE & REST OF MAHARASHTRA ---
    {
        "code": "PUNE",
        "name": "Pune Junction",
        "city": "Pune",
        "state": "Maharashtra",
        "zone": "CR",
        "division": "Pune",
        "search_aliases": "pune, poona, pune jn",
        "is_major": True,
        "is_junction": True,
        "platform_count": 6,
        "latitude": 18.5289,
        "longitude": 73.8744,
    },
    {
        "code": "LNL",
        "name": "Lonavala",
        "city": "Lonavala",
        "state": "Maharashtra",
        "zone": "CR",
        "division": "Mumbai",
        "search_aliases": "lonavla, khandala, lnl",
        "is_major": True,
        "is_junction": True,
        "platform_count": 3,
        "latitude": 18.7513,
        "longitude": 73.4072,
    },
    {
        "code": "DD",
        "name": "Daund Junction",
        "city": "Daund",
        "state": "Maharashtra",
        "zone": "CR",
        "division": "Pune",
        "search_aliases": "daund, daund jn, dd",
        "is_major": True,
        "is_junction": True,
        "platform_count": 6,
        "latitude": 18.4636,
        "longitude": 74.5828,
    },
    {
        "code": "SUR",
        "name": "Solapur",
        "city": "Solapur",
        "state": "Maharashtra",
        "zone": "CR",
        "division": "Solapur",
        "search_aliases": "sholapur, solapur, sur",
        "is_major": True,
        "is_junction": True,
        "platform_count": 5,
        "latitude": 17.6599,
        "longitude": 75.9064,
    },
    {
        "code": "NK",
        "name": "Nashik Road",
        "city": "Nashik",
        "state": "Maharashtra",
        "zone": "CR",
        "division": "Bhusawal",
        "search_aliases": "nasik, nashik, nasik road, nk",
        "is_major": True,
        "is_junction": False,
        "platform_count": 4,
        "latitude": 19.9547,
        "longitude": 73.8373,
    },
    {
        "code": "MMR",
        "name": "Manmad Junction",
        "city": "Manmad",
        "state": "Maharashtra",
        "zone": "CR",
        "division": "Bhusawal",
        "search_aliases": "manmad, mmr, shirdi junction",
        "is_major": True,
        "is_junction": True,
        "platform_count": 6,
        "latitude": 20.2528,
        "longitude": 74.4361,
    },
    {
        "code": "SNSI",
        "name": "Sainagar Shirdi",
        "city": "Shirdi",
        "state": "Maharashtra",
        "zone": "CR",
        "division": "Solapur",
        "search_aliases": "shirdi, sai nagar shirdi, snsi, saibaba",
        "is_major": True,
        "is_junction": False,
        "platform_count": 3,
        "latitude": 19.7719,
        "longitude": 74.4878,
    },
    {
        "code": "KPG",
        "name": "Kopargaon",
        "city": "Kopargaon",
        "state": "Maharashtra",
        "zone": "CR",
        "division": "Solapur",
        "search_aliases": "kopargaon, shirdi kopargaon, kpg",
        "is_major": False,
        "is_junction": False,
        "platform_count": 2,
        "latitude": 19.8833,
        "longitude": 74.4833,
    },
    {
        "code": "BSL",
        "name": "Bhusaval Junction",
        "city": "Bhusawal",
        "state": "Maharashtra",
        "zone": "CR",
        "division": "Bhusawal",
        "search_aliases": "bhusawal, bhusaval, bsl",
        "is_major": True,
        "is_junction": True,
        "platform_count": 8,
        "latitude": 21.0456,
        "longitude": 75.8011,
    },
    {
        "code": "JL",
        "name": "Jalgaon Junction",
        "city": "Jalgaon",
        "state": "Maharashtra",
        "zone": "CR",
        "division": "Bhusawal",
        "search_aliases": "jalgaon, jl",
        "is_major": True,
        "is_junction": True,
        "platform_count": 5,
        "latitude": 21.0077,
        "longitude": 75.5626,
    },
    {
        "code": "AK",
        "name": "Akola Junction",
        "city": "Akola",
        "state": "Maharashtra",
        "zone": "CR",
        "division": "Bhusawal",
        "search_aliases": "akola, akola jn, ak",
        "is_major": True,
        "is_junction": True,
        "platform_count": 6,
        "latitude": 20.7002,
        "longitude": 77.0082,
    },
    {
        "code": "BD",
        "name": "Badnera Junction",
        "city": "Amravati",
        "state": "Maharashtra",
        "zone": "CR",
        "division": "Bhusawal",
        "search_aliases": "amravati, badnera, bd",
        "is_major": True,
        "is_junction": True,
        "platform_count": 4,
        "latitude": 20.8628,
        "longitude": 77.7289,
    },
    {
        "code": "NGP",
        "name": "Nagpur Junction",
        "city": "Nagpur",
        "state": "Maharashtra",
        "zone": "CR",
        "division": "Nagpur",
        "search_aliases": "nagpur, nagpur jn, ngp",
        "is_major": True,
        "is_junction": True,
        "platform_count": 8,
        "latitude": 21.1528,
        "longitude": 79.0882,
    },
    {
        "code": "WR",
        "name": "Wardha Junction",
        "city": "Wardha",
        "state": "Maharashtra",
        "zone": "CR",
        "division": "Nagpur",
        "search_aliases": "wardha, wr",
        "is_major": True,
        "is_junction": True,
        "platform_count": 4,
        "latitude": 20.7453,
        "longitude": 78.5972,
    },
    {
        "code": "AWB",
        "name": "Chhatrapati Sambhajinagar (Aurangabad)",
        "city": "Aurangabad",
        "state": "Maharashtra",
        "zone": "SCR",
        "division": "Nanded",
        "search_aliases": "aurangabad, sambhajinagar, awb",
        "is_major": True,
        "is_junction": False,
        "platform_count": 4,
        "latitude": 19.8661,
        "longitude": 75.3181,
    },
    {
        "code": "NED",
        "name": "Hazur Sahib Nanded",
        "city": "Nanded",
        "state": "Maharashtra",
        "zone": "SCR",
        "division": "Nanded",
        "search_aliases": "nanded, hazur sahib, ned",
        "is_major": True,
        "is_junction": True,
        "platform_count": 4,
        "latitude": 19.1558,
        "longitude": 77.3197,
    },
    {
        "code": "KOP",
        "name": "Kolhapur CSMT",
        "city": "Kolhapur",
        "state": "Maharashtra",
        "zone": "CR",
        "division": "Pune",
        "search_aliases": "kolhapur, shahu maharaj terminus, kop",
        "is_major": True,
        "is_junction": False,
        "platform_count": 3,
        "latitude": 16.7028,
        "longitude": 74.2406,
    },
    {
        "code": "MRJ",
        "name": "Miraj Junction",
        "city": "Miraj",
        "state": "Maharashtra",
        "zone": "CR",
        "division": "Pune",
        "search_aliases": "miraj, sangli miraj, mrj",
        "is_major": True,
        "is_junction": True,
        "platform_count": 6,
        "latitude": 16.8258,
        "longitude": 74.6469,
    },

    # --- DELHI NCR & NORTHERN RAILWAYS ---
    {
        "code": "NDLS",
        "name": "New Delhi",
        "city": "Delhi",
        "state": "Delhi",
        "zone": "NR",
        "division": "Delhi",
        "search_aliases": "new delhi, ndls, delhi ndls, delhi",
        "is_major": True,
        "is_junction": True,
        "platform_count": 16,
        "latitude": 28.6415,
        "longitude": 77.2207,
    },
    {
        "code": "DLI",
        "name": "Old Delhi Junction",
        "city": "Delhi",
        "state": "Delhi",
        "zone": "NR",
        "division": "Delhi",
        "search_aliases": "old delhi, dli, delhi junction, delhi",
        "is_major": True,
        "is_junction": True,
        "platform_count": 16,
        "latitude": 28.6607,
        "longitude": 77.2285,
    },
    {
        "code": "NZM",
        "name": "Hazrat Nizamuddin",
        "city": "Delhi",
        "state": "Delhi",
        "zone": "NR",
        "division": "Delhi",
        "search_aliases": "nizamuddin, nzm, h nizamuddin, delhi nizamuddin, delhi",
        "is_major": True,
        "is_junction": True,
        "platform_count": 8,
        "latitude": 28.5889,
        "longitude": 77.2536,
    },
    {
        "code": "ANVT",
        "name": "Anand Vihar Terminal",
        "city": "Delhi",
        "state": "Delhi",
        "zone": "NR",
        "division": "Delhi",
        "search_aliases": "anand vihar, anvt, anand vihar delhi, delhi",
        "is_major": True,
        "is_junction": False,
        "platform_count": 7,
        "latitude": 28.6508,
        "longitude": 77.3153,
    },
    {
        "code": "DEE",
        "name": "Delhi Sarai Rohilla",
        "city": "Delhi",
        "state": "Delhi",
        "zone": "NR",
        "division": "Delhi",
        "search_aliases": "sarai rohilla, dee, delhi sarai rohilla, delhi",
        "is_major": True,
        "is_junction": False,
        "platform_count": 7,
        "latitude": 28.6617,
        "longitude": 77.1814,
    },
    {
        "code": "GZB",
        "name": "Ghaziabad Junction",
        "city": "Ghaziabad",
        "state": "Uttar Pradesh",
        "zone": "NR",
        "division": "Delhi",
        "search_aliases": "ghaziabad, gzb",
        "is_major": True,
        "is_junction": True,
        "platform_count": 6,
        "latitude": 28.6675,
        "longitude": 77.4378,
    },
    {
        "code": "UMB",
        "name": "Ambala Cantt Junction",
        "city": "Ambala",
        "state": "Haryana",
        "zone": "NR",
        "division": "Ambala",
        "search_aliases": "ambala, ambala cantt, umb",
        "is_major": True,
        "is_junction": True,
        "platform_count": 8,
        "latitude": 30.3472,
        "longitude": 76.8228,
    },
    {
        "code": "CDG",
        "name": "Chandigarh Junction",
        "city": "Chandigarh",
        "state": "Chandigarh",
        "zone": "NR",
        "division": "Ambala",
        "search_aliases": "chandigarh, cdg",
        "is_major": True,
        "is_junction": True,
        "platform_count": 6,
        "latitude": 30.7058,
        "longitude": 76.8228,
    },
    {
        "code": "LDH",
        "name": "Ludhiana Junction",
        "city": "Ludhiana",
        "state": "Punjab",
        "zone": "NR",
        "division": "Firozpur",
        "search_aliases": "ludhiana, ldh",
        "is_major": True,
        "is_junction": True,
        "platform_count": 7,
        "latitude": 30.9128,
        "longitude": 75.8572,
    },
    {
        "code": "JUC",
        "name": "Jalandhar City Junction",
        "city": "Jalandhar",
        "state": "Punjab",
        "zone": "NR",
        "division": "Firozpur",
        "search_aliases": "jalandhar, jalandhar city, juc",
        "is_major": True,
        "is_junction": True,
        "platform_count": 5,
        "latitude": 31.3325,
        "longitude": 75.5861,
    },
    {
        "code": "ASR",
        "name": "Amritsar Junction",
        "city": "Amritsar",
        "state": "Punjab",
        "zone": "NR",
        "division": "Firozpur",
        "search_aliases": "amritsar, golden temple, asr",
        "is_major": True,
        "is_junction": True,
        "platform_count": 8,
        "latitude": 31.6339,
        "longitude": 74.8656,
    },
    {
        "code": "JAT",
        "name": "Jammu Tawi",
        "city": "Jammu",
        "state": "Jammu and Kashmir",
        "zone": "NR",
        "division": "Firozpur",
        "search_aliases": "jammu, jammu tawi, jat",
        "is_major": True,
        "is_junction": False,
        "platform_count": 4,
        "latitude": 32.7058,
        "longitude": 74.8778,
    },
    {
        "code": "SVDK",
        "name": "SMVD Katra",
        "city": "Katra",
        "state": "Jammu and Kashmir",
        "zone": "NR",
        "division": "Firozpur",
        "search_aliases": "katra, vaishno devi, svdk",
        "is_major": True,
        "is_junction": False,
        "platform_count": 5,
        "latitude": 32.9933,
        "longitude": 74.9317,
    },
    {
        "code": "HW",
        "name": "Haridwar",
        "city": "Haridwar",
        "state": "Uttarakhand",
        "zone": "NR",
        "division": "Moradabad",
        "search_aliases": "haridwar, hardwar, hw",
        "is_major": True,
        "is_junction": True,
        "platform_count": 9,
        "latitude": 29.9458,
        "longitude": 78.1561,
    },
    {
        "code": "DDN",
        "name": "Dehradun",
        "city": "Dehradun",
        "state": "Uttarakhand",
        "zone": "NR",
        "division": "Moradabad",
        "search_aliases": "dehradun, ddn, mussoorie",
        "is_major": True,
        "is_junction": False,
        "platform_count": 4,
        "latitude": 30.3158,
        "longitude": 78.0353,
    },

    # --- GUJARAT & WESTERN ZONE ---
    {
        "code": "ST",
        "name": "Surat",
        "city": "Surat",
        "state": "Gujarat",
        "zone": "WR",
        "division": "Mumbai",
        "search_aliases": "surat, st",
        "is_major": True,
        "is_junction": True,
        "platform_count": 6,
        "latitude": 21.2049,
        "longitude": 72.8406,
    },
    {
        "code": "BRC",
        "name": "Vadodara Junction",
        "city": "Vadodara",
        "state": "Gujarat",
        "zone": "WR",
        "division": "Vadodara",
        "search_aliases": "baroda, vadodara, brc",
        "is_major": True,
        "is_junction": True,
        "platform_count": 7,
        "latitude": 22.3108,
        "longitude": 73.1812,
    },
    {
        "code": "ADI",
        "name": "Ahmedabad Junction",
        "city": "Ahmedabad",
        "state": "Gujarat",
        "zone": "WR",
        "division": "Ahmedabad",
        "search_aliases": "ahmedabad, kalupur, adi, amdavad",
        "is_major": True,
        "is_junction": True,
        "platform_count": 12,
        "latitude": 23.0238,
        "longitude": 72.6006,
    },
    {
        "code": "GNC",
        "name": "Gandhinagar Capital",
        "city": "Gandhinagar",
        "state": "Gujarat",
        "zone": "WR",
        "division": "Ahmedabad",
        "search_aliases": "gandhinagar, gnc",
        "is_major": True,
        "is_junction": False,
        "platform_count": 3,
        "latitude": 23.2389,
        "longitude": 72.6517,
    },
    {
        "code": "ANND",
        "name": "Anand Junction",
        "city": "Anand",
        "state": "Gujarat",
        "zone": "WR",
        "division": "Vadodara",
        "search_aliases": "anand, amul, annd",
        "is_major": True,
        "is_junction": True,
        "platform_count": 6,
        "latitude": 22.5639,
        "longitude": 72.9511,
    },
    {
        "code": "RJT",
        "name": "Rajkot Junction",
        "city": "Rajkot",
        "state": "Gujarat",
        "zone": "WR",
        "division": "Rajkot",
        "search_aliases": "rajkot, rjt, saurashtra",
        "is_major": True,
        "is_junction": True,
        "platform_count": 5,
        "latitude": 22.3117,
        "longitude": 70.8022,
    },
    {
        "code": "BHUJ",
        "name": "Bhuj",
        "city": "Bhuj",
        "state": "Gujarat",
        "zone": "WR",
        "division": "Ahmedabad",
        "search_aliases": "bhuj, kutch, bhuj",
        "is_major": True,
        "is_junction": False,
        "platform_count": 3,
        "latitude": 23.2536,
        "longitude": 69.6739,
    },

    # --- RAJASTHAN ---
    {
        "code": "JP",
        "name": "Jaipur Junction",
        "city": "Jaipur",
        "state": "Rajasthan",
        "zone": "NWR",
        "division": "Jaipur",
        "search_aliases": "jaipur, pink city, jp",
        "is_major": True,
        "is_junction": True,
        "platform_count": 8,
        "latitude": 26.9196,
        "longitude": 75.7878,
    },
    {
        "code": "AII",
        "name": "Ajmer Junction",
        "city": "Ajmer",
        "state": "Rajasthan",
        "zone": "NWR",
        "division": "Ajmer",
        "search_aliases": "ajmer, pushkar, aii",
        "is_major": True,
        "is_junction": True,
        "platform_count": 5,
        "latitude": 26.4528,
        "longitude": 74.6397,
    },
    {
        "code": "JU",
        "name": "Jodhpur",
        "city": "Jodhpur",
        "state": "Rajasthan",
        "zone": "NWR",
        "division": "Jodhpur",
        "search_aliases": "jodhpur, sun city, ju",
        "is_major": True,
        "is_junction": True,
        "platform_count": 5,
        "latitude": 26.2894,
        "longitude": 73.0189,
    },
    {
        "code": "BKN",
        "name": "Bikaner Junction",
        "city": "Bikaner",
        "state": "Rajasthan",
        "zone": "NWR",
        "division": "Bikaner",
        "search_aliases": "bikaner, bkn",
        "is_major": True,
        "is_junction": True,
        "platform_count": 6,
        "latitude": 28.0186,
        "longitude": 73.3139,
    },
    {
        "code": "KOTA",
        "name": "Kota Junction",
        "city": "Kota",
        "state": "Rajasthan",
        "zone": "WCR",
        "division": "Kota",
        "search_aliases": "kota, kota jn, coaching hub",
        "is_major": True,
        "is_junction": True,
        "platform_count": 5,
        "latitude": 25.2189,
        "longitude": 75.8647,
    },
    {
        "code": "UDZ",
        "name": "Udaipur City",
        "city": "Udaipur",
        "state": "Rajasthan",
        "zone": "NWR",
        "division": "Ajmer",
        "search_aliases": "udaipur, lake city, udz",
        "is_major": True,
        "is_junction": False,
        "platform_count": 5,
        "latitude": 24.5714,
        "longitude": 73.6983,
    },

    # --- UTTAR PRADESH & BIHAR ---
    {
        "code": "AGC",
        "name": "Agra Cantt",
        "city": "Agra",
        "state": "Uttar Pradesh",
        "zone": "NCR",
        "division": "Agra",
        "search_aliases": "agra, taj mahal, agc, agra cantt",
        "is_major": True,
        "is_junction": True,
        "platform_count": 6,
        "latitude": 27.1583,
        "longitude": 77.9894,
    },
    {
        "code": "MTJ",
        "name": "Mathura Junction",
        "city": "Mathura",
        "state": "Uttar Pradesh",
        "zone": "NCR",
        "division": "Agra",
        "search_aliases": "mathura, vrindavan, mtj",
        "is_major": True,
        "is_junction": True,
        "platform_count": 10,
        "latitude": 27.4925,
        "longitude": 77.6736,
    },
    {
        "code": "CNB",
        "name": "Kanpur Central",
        "city": "Kanpur",
        "state": "Uttar Pradesh",
        "zone": "NCR",
        "division": "Prayagraj",
        "search_aliases": "kanpur, cawnpore, cnb",
        "is_major": True,
        "is_junction": True,
        "platform_count": 10,
        "latitude": 26.4539,
        "longitude": 80.3517,
    },
    {
        "code": "LKO",
        "name": "Lucknow Charbagh",
        "city": "Lucknow",
        "state": "Uttar Pradesh",
        "zone": "NR",
        "division": "Lucknow NR",
        "search_aliases": "lucknow, charbagh, lko, lakhnau",
        "is_major": True,
        "is_junction": True,
        "platform_count": 9,
        "latitude": 26.8319,
        "longitude": 80.9197,
    },
    {
        "code": "PRYJ",
        "name": "Prayagraj Junction",
        "city": "Prayagraj",
        "state": "Uttar Pradesh",
        "zone": "NCR",
        "division": "Prayagraj",
        "search_aliases": "allahabad, prayag, sangam, pryj, ald",
        "is_major": True,
        "is_junction": True,
        "platform_count": 10,
        "latitude": 25.4489,
        "longitude": 81.8267,
    },
    {
        "code": "BSB",
        "name": "Varanasi Junction",
        "city": "Varanasi",
        "state": "Uttar Pradesh",
        "zone": "NR",
        "division": "Lucknow NR",
        "search_aliases": "varanasi, banaras, kashi, bsb",
        "is_major": True,
        "is_junction": True,
        "platform_count": 9,
        "latitude": 25.3283,
        "longitude": 82.9864,
    },
    {
        "code": "DDU",
        "name": "Pt. Deen Dayal Upadhyaya Junction",
        "city": "Mughalsarai",
        "state": "Uttar Pradesh",
        "zone": "ECR",
        "division": "Pt. Deen Dayal Upadhyaya",
        "search_aliases": "mughalsarai, deen dayal, ddu, mgs",
        "is_major": True,
        "is_junction": True,
        "platform_count": 8,
        "latitude": 25.2764,
        "longitude": 83.1189,
    },
    {
        "code": "GKP",
        "name": "Gorakhpur Junction",
        "city": "Gorakhpur",
        "state": "Uttar Pradesh",
        "zone": "NER",
        "division": "Lucknow NER",
        "search_aliases": "gorakhpur, gkp, longest platform",
        "is_major": True,
        "is_junction": True,
        "platform_count": 10,
        "latitude": 26.7606,
        "longitude": 83.3769,
    },
    {
        "code": "AY",
        "name": "Ayodhya Dham Junction",
        "city": "Ayodhya",
        "state": "Uttar Pradesh",
        "zone": "NR",
        "division": "Lucknow NR",
        "search_aliases": "ayodhya, ram mandir, ay, faizabad",
        "is_major": True,
        "is_junction": True,
        "platform_count": 6,
        "latitude": 26.7925,
        "longitude": 82.2036,
    },
    {
        "code": "PNBE",
        "name": "Patna Junction",
        "city": "Patna",
        "state": "Bihar",
        "zone": "ECR",
        "division": "Danapur",
        "search_aliases": "patna, patliputra, pnbe",
        "is_major": True,
        "is_junction": True,
        "platform_count": 10,
        "latitude": 25.6022,
        "longitude": 85.1378,
    },
    {
        "code": "GAYA",
        "name": "Gaya Junction",
        "city": "Gaya",
        "state": "Bihar",
        "zone": "ECR",
        "division": "Pt. Deen Dayal Upadhyaya",
        "search_aliases": "gaya, bodhgaya, bodh gaya, gaya jn",
        "is_major": True,
        "is_junction": True,
        "platform_count": 9,
        "latitude": 24.8089,
        "longitude": 84.9989,
    },
    {
        "code": "MFP",
        "name": "Muzaffarpur Junction",
        "city": "Muzaffarpur",
        "state": "Bihar",
        "zone": "ECR",
        "division": "Sonpur",
        "search_aliases": "muzaffarpur, litchi city, mfp",
        "is_major": True,
        "is_junction": True,
        "platform_count": 8,
        "latitude": 26.1208,
        "longitude": 85.3853,
    },

    # --- MADHYA PRADESH & CHHATTISGARH ---
    {
        "code": "BPL",
        "name": "Bhopal Junction",
        "city": "Bhopal",
        "state": "Madhya Pradesh",
        "zone": "WCR",
        "division": "Bhopal",
        "search_aliases": "bhopal, lake city, bpl",
        "is_major": True,
        "is_junction": True,
        "platform_count": 6,
        "latitude": 23.2658,
        "longitude": 77.4128,
    },
    {
        "code": "RKMP",
        "name": "Rani Kamalapati",
        "city": "Bhopal",
        "state": "Madhya Pradesh",
        "zone": "WCR",
        "division": "Bhopal",
        "search_aliases": "habibganj, rani kamalapati, rkmp, world class station",
        "is_major": True,
        "is_junction": False,
        "platform_count": 5,
        "latitude": 23.2089,
        "longitude": 77.4372,
    },
    {
        "code": "GWL",
        "name": "Gwalior Junction",
        "city": "Gwalior",
        "state": "Madhya Pradesh",
        "zone": "NCR",
        "division": "Jhansi",
        "search_aliases": "gwalior, gwl",
        "is_major": True,
        "is_junction": True,
        "platform_count": 5,
        "latitude": 26.2167,
        "longitude": 78.1889,
    },
    {
        "code": "VGLJ",
        "name": "V Lakshmibai Jhansi",
        "city": "Jhansi",
        "state": "Uttar Pradesh",
        "zone": "NCR",
        "division": "Jhansi",
        "search_aliases": "jhansi, jhs, virangana lakshmibai, vglj",
        "is_major": True,
        "is_junction": True,
        "platform_count": 8,
        "latitude": 25.4489,
        "longitude": 78.5583,
    },
    {
        "code": "INDB",
        "name": "Indore Junction",
        "city": "Indore",
        "state": "Madhya Pradesh",
        "zone": "WR",
        "division": "Ratlam",
        "search_aliases": "indore, cleanest city, indb",
        "is_major": True,
        "is_junction": True,
        "platform_count": 6,
        "latitude": 22.7178,
        "longitude": 75.8683,
    },
    {
        "code": "UJN",
        "name": "Ujjain Junction",
        "city": "Ujjain",
        "state": "Madhya Pradesh",
        "zone": "WR",
        "division": "Ratlam",
        "search_aliases": "ujjain, mahakal, ujn",
        "is_major": True,
        "is_junction": True,
        "platform_count": 8,
        "latitude": 23.1817,
        "longitude": 75.7778,
    },
    {
        "code": "JBP",
        "name": "Jabalpur",
        "city": "Jabalpur",
        "state": "Madhya Pradesh",
        "zone": "WCR",
        "division": "Jabalpur",
        "search_aliases": "jabalpur, bhedaghat, jbp",
        "is_major": True,
        "is_junction": True,
        "platform_count": 6,
        "latitude": 23.1658,
        "longitude": 79.9483,
    },
    {
        "code": "R",
        "name": "Raipur Junction",
        "city": "Raipur",
        "state": "Chhattisgarh",
        "zone": "SECR",
        "division": "Raipur",
        "search_aliases": "raipur, chhattisgarh, r",
        "is_major": True,
        "is_junction": True,
        "platform_count": 7,
        "latitude": 21.2589,
        "longitude": 81.6319,
    },
    {
        "code": "BSP",
        "name": "Bilaspur Junction",
        "city": "Bilaspur",
        "state": "Chhattisgarh",
        "zone": "SECR",
        "division": "Bilaspur",
        "search_aliases": "bilaspur, bsp",
        "is_major": True,
        "is_junction": True,
        "platform_count": 8,
        "latitude": 22.0789,
        "longitude": 82.1647,
    },

    # --- WEST BENGAL & EASTERN ZONE ---
    {
        "code": "HWH",
        "name": "Howrah Junction",
        "city": "Kolkata",
        "state": "West Bengal",
        "zone": "ER",
        "division": "Howrah",
        "search_aliases": "howrah, kolkata, calcutta, hwh",
        "is_major": True,
        "is_junction": True,
        "platform_count": 23,
        "latitude": 22.5839,
        "longitude": 88.3426,
    },
    {
        "code": "SDAH",
        "name": "Sealdah",
        "city": "Kolkata",
        "state": "West Bengal",
        "zone": "ER",
        "division": "Sealdah",
        "search_aliases": "sealdah, kolkata sealdah, calcutta sealdah, sdah",
        "is_major": True,
        "is_junction": True,
        "platform_count": 21,
        "latitude": 22.5678,
        "longitude": 88.3714,
    },
    {
        "code": "KOAA",
        "name": "Kolkata Terminal",
        "city": "Kolkata",
        "state": "West Bengal",
        "zone": "ER",
        "division": "Sealdah",
        "search_aliases": "chitpur, kolkata terminal, koaa",
        "is_major": True,
        "is_junction": False,
        "platform_count": 5,
        "latitude": 22.6025,
        "longitude": 88.3769,
    },
    {
        "code": "KGP",
        "name": "Kharagpur Junction",
        "city": "Kharagpur",
        "state": "West Bengal",
        "zone": "SER",
        "division": "Kharagpur",
        "search_aliases": "kharagpur, iit kgp, kgp",
        "is_major": True,
        "is_junction": True,
        "platform_count": 12,
        "latitude": 22.3389,
        "longitude": 87.3217,
    },
    {
        "code": "ASN",
        "name": "Asansol Junction",
        "city": "Asansol",
        "state": "West Bengal",
        "zone": "ER",
        "division": "Asansol",
        "search_aliases": "asansol, asn",
        "is_major": True,
        "is_junction": True,
        "platform_count": 8,
        "latitude": 23.6872,
        "longitude": 86.9739,
    },
    {
        "code": "NJP",
        "name": "New Jalpaiguri",
        "city": "Siliguri",
        "state": "West Bengal",
        "zone": "NFR",
        "division": "Katihar",
        "search_aliases": "siliguri, darjeeling, new jalpaiguri, njp",
        "is_major": True,
        "is_junction": True,
        "platform_count": 8,
        "latitude": 26.6853,
        "longitude": 88.4419,
    },
    {
        "code": "GHY",
        "name": "Guwahati",
        "city": "Guwahati",
        "state": "Assam",
        "zone": "NFR",
        "division": "Lumding",
        "search_aliases": "guwahati, gauhati, kamakhya, assam, ghy",
        "is_major": True,
        "is_junction": True,
        "platform_count": 7,
        "latitude": 26.1839,
        "longitude": 91.7508,
    },
    {
        "code": "BBS",
        "name": "Bhubaneswar",
        "city": "Bhubaneswar",
        "state": "Odisha",
        "zone": "ECoR",
        "division": "Khurda Road",
        "search_aliases": "bhubaneswar, temple city, bbs, orissa",
        "is_major": True,
        "is_junction": True,
        "platform_count": 6,
        "latitude": 20.2689,
        "longitude": 85.8439,
    },
    {
        "code": "PURI",
        "name": "Puri",
        "city": "Puri",
        "state": "Odisha",
        "zone": "ECoR",
        "division": "Khurda Road",
        "search_aliases": "puri, jagannath puri, puri dham",
        "is_major": True,
        "is_junction": False,
        "platform_count": 8,
        "latitude": 19.8139,
        "longitude": 85.8317,
    },
    {
        "code": "TATA",
        "name": "Tatanagar Junction",
        "city": "Jamshedpur",
        "state": "Jharkhand",
        "zone": "SER",
        "division": "Chakradharpur",
        "search_aliases": "jamshedpur, tatanagar, tata, steel city",
        "is_major": True,
        "is_junction": True,
        "platform_count": 5,
        "latitude": 22.7667,
        "longitude": 86.2028,
    },
    {
        "code": "DHN",
        "name": "Dhanbad Junction",
        "city": "Dhanbad",
        "state": "Jharkhand",
        "zone": "ECR",
        "division": "Dhanbad",
        "search_aliases": "dhanbad, coal capital, dhn",
        "is_major": True,
        "is_junction": True,
        "platform_count": 8,
        "latitude": 23.7925,
        "longitude": 86.4308,
    },
    {
        "code": "RNC",
        "name": "Ranchi Junction",
        "city": "Ranchi",
        "state": "Jharkhand",
        "zone": "SER",
        "division": "Ranchi",
        "search_aliases": "ranchi, rnc",
        "is_major": True,
        "is_junction": True,
        "platform_count": 6,
        "latitude": 23.3517,
        "longitude": 85.3378,
    },

    # --- TAMIL NADU & CHENNAI ---
    {
        "code": "MAS",
        "name": "MGR Chennai Central",
        "city": "Chennai",
        "state": "Tamil Nadu",
        "zone": "SR",
        "division": "Chennai",
        "search_aliases": "chennai central, madras, madras central, mas",
        "is_major": True,
        "is_junction": True,
        "platform_count": 17,
        "latitude": 13.0827,
        "longitude": 80.2755,
    },
    {
        "code": "MS",
        "name": "Chennai Egmore",
        "city": "Chennai",
        "state": "Tamil Nadu",
        "zone": "SR",
        "division": "Chennai",
        "search_aliases": "chennai egmore, egmore, ms, madras egmore",
        "is_major": True,
        "is_junction": True,
        "platform_count": 11,
        "latitude": 13.0789,
        "longitude": 80.2619,
    },
    {
        "code": "TBM",
        "name": "Tambaram",
        "city": "Chennai",
        "state": "Tamil Nadu",
        "zone": "SR",
        "division": "Chennai",
        "search_aliases": "tambaram, tbm",
        "is_major": True,
        "is_junction": True,
        "platform_count": 8,
        "latitude": 12.9247,
        "longitude": 80.1178,
    },
    {
        "code": "CBE",
        "name": "Coimbatore Junction",
        "city": "Coimbatore",
        "state": "Tamil Nadu",
        "zone": "SR",
        "division": "Salem",
        "search_aliases": "coimbatore, kovai, cbe",
        "is_major": True,
        "is_junction": True,
        "platform_count": 6,
        "latitude": 10.9989,
        "longitude": 76.9658,
    },
    {
        "code": "MDU",
        "name": "Madurai Junction",
        "city": "Madurai",
        "state": "Tamil Nadu",
        "zone": "SR",
        "division": "Madurai",
        "search_aliases": "madurai, temple city, mdu",
        "is_major": True,
        "is_junction": True,
        "platform_count": 8,
        "latitude": 9.9253,
        "longitude": 78.1114,
    },
    {
        "code": "TPJ",
        "name": "Tiruchchirappalli Junction",
        "city": "Tiruchirappalli",
        "state": "Tamil Nadu",
        "zone": "SR",
        "division": "Tiruchirappalli",
        "search_aliases": "trichy, tiruchi, tpj",
        "is_major": True,
        "is_junction": True,
        "platform_count": 8,
        "latitude": 10.7936,
        "longitude": 78.6853,
    },
    {
        "code": "SA",
        "name": "Salem Junction",
        "city": "Salem",
        "state": "Tamil Nadu",
        "zone": "SR",
        "division": "Salem",
        "search_aliases": "salem, sa",
        "is_major": True,
        "is_junction": True,
        "platform_count": 6,
        "latitude": 11.6644,
        "longitude": 78.1286,
    },
    {
        "code": "RMM",
        "name": "Rameswaram",
        "city": "Rameswaram",
        "state": "Tamil Nadu",
        "zone": "SR",
        "division": "Madurai",
        "search_aliases": "rameswaram, rameshwaram, rmm, pamban",
        "is_major": True,
        "is_junction": False,
        "platform_count": 4,
        "latitude": 9.2889,
        "longitude": 79.3128,
    },

    # --- KARNATAKA ---
    {
        "code": "SBC",
        "name": "KSR Bengaluru City",
        "city": "Bengaluru",
        "state": "Karnataka",
        "zone": "SWR",
        "division": "Bengaluru",
        "search_aliases": "bangalore, bangalore city, bengaluru, sbc, ksr bengaluru",
        "is_major": True,
        "is_junction": True,
        "platform_count": 10,
        "latitude": 12.9784,
        "longitude": 77.5694,
    },
    {
        "code": "YPR",
        "name": "Yesvantpur Junction",
        "city": "Bengaluru",
        "state": "Karnataka",
        "zone": "SWR",
        "division": "Bengaluru",
        "search_aliases": "yesvantpur, yeshwantpur, ypr, bangalore north",
        "is_major": True,
        "is_junction": True,
        "platform_count": 6,
        "latitude": 13.0236,
        "longitude": 77.5508,
    },
    {
        "code": "SMVB",
        "name": "SMVT Bengaluru",
        "city": "Bengaluru",
        "state": "Karnataka",
        "zone": "SWR",
        "division": "Bengaluru",
        "search_aliases": "baiyappanahalli, smvt, smvb, sir m visvesvaraya",
        "is_major": True,
        "is_junction": False,
        "platform_count": 7,
        "latitude": 13.0033,
        "longitude": 77.6536,
    },
    {
        "code": "MYS",
        "name": "Mysuru Junction",
        "city": "Mysuru",
        "state": "Karnataka",
        "zone": "SWR",
        "division": "Mysuru",
        "search_aliases": "mysore, mysuru, palace city, mys",
        "is_major": True,
        "is_junction": True,
        "platform_count": 6,
        "latitude": 12.3161,
        "longitude": 76.6453,
    },
    {
        "code": "UBL",
        "name": "SSS Hubballi Junction",
        "city": "Hubballi",
        "state": "Karnataka",
        "zone": "SWR",
        "division": "Hubballi",
        "search_aliases": "hubli, hubballi, ubl, longest platform in world",
        "is_major": True,
        "is_junction": True,
        "platform_count": 8,
        "latitude": 15.3489,
        "longitude": 75.1489,
    },
    {
        "code": "MAQ",
        "name": "Mangaluru Central",
        "city": "Mangaluru",
        "state": "Karnataka",
        "zone": "SR",
        "division": "Palakkad",
        "search_aliases": "mangalore, mangaluru central, maq",
        "is_major": True,
        "is_junction": True,
        "platform_count": 4,
        "latitude": 12.8653,
        "longitude": 74.8428,
    },

    # --- KERALA ---
    {
        "code": "TVC",
        "name": "Thiruvananthapuram Central",
        "city": "Thiruvananthapuram",
        "state": "Kerala",
        "zone": "SR",
        "division": "Thiruvananthapuram",
        "search_aliases": "trivandrum, thiruvananthapuram, tvc, kerala capital",
        "is_major": True,
        "is_junction": True,
        "platform_count": 5,
        "latitude": 8.4869,
        "longitude": 76.9528,
    },
    {
        "code": "ERS",
        "name": "Ernakulam Junction (South)",
        "city": "Kochi",
        "state": "Kerala",
        "zone": "SR",
        "division": "Thiruvananthapuram",
        "search_aliases": "kochi, cochin, ernakulam, ernakulam south, ers",
        "is_major": True,
        "is_junction": True,
        "platform_count": 6,
        "latitude": 9.9678,
        "longitude": 76.2917,
    },
    {
        "code": "ERN",
        "name": "Ernakulam Town (North)",
        "city": "Kochi",
        "state": "Kerala",
        "zone": "SR",
        "division": "Thiruvananthapuram",
        "search_aliases": "ernakulam north, ern, kochi north",
        "is_major": True,
        "is_junction": False,
        "platform_count": 2,
        "latitude": 9.9989,
        "longitude": 76.2894,
    },
    {
        "code": "CLT",
        "name": "Kozhikode Main",
        "city": "Kozhikode",
        "state": "Kerala",
        "zone": "SR",
        "division": "Palakkad",
        "search_aliases": "calicut, kozhikode, clt",
        "is_major": True,
        "is_junction": True,
        "platform_count": 4,
        "latitude": 11.2464,
        "longitude": 75.7828,
    },

    # --- TELANGANA & ANDHRA PRADESH ---
    {
        "code": "SC",
        "name": "Secunderabad Junction",
        "city": "Hyderabad",
        "state": "Telangana",
        "zone": "SCR",
        "division": "Secunderabad",
        "search_aliases": "secunderabad, hyderabad secunderabad, sc",
        "is_major": True,
        "is_junction": True,
        "platform_count": 10,
        "latitude": 17.4344,
        "longitude": 78.5015,
    },
    {
        "code": "HYB",
        "name": "Hyderabad Deccan (Nampally)",
        "city": "Hyderabad",
        "state": "Telangana",
        "zone": "SCR",
        "division": "Hyderabad",
        "search_aliases": "nampally, hyderabad, hyb",
        "is_major": True,
        "is_junction": False,
        "platform_count": 6,
        "latitude": 17.3917,
        "longitude": 78.4686,
    },
    {
        "code": "KCG",
        "name": "Kacheguda",
        "city": "Hyderabad",
        "state": "Telangana",
        "zone": "SCR",
        "division": "Hyderabad",
        "search_aliases": "kacheguda, hyderabad kacheguda, kcg",
        "is_major": True,
        "is_junction": False,
        "platform_count": 5,
        "latitude": 17.3872,
        "longitude": 78.4975,
    },
    {
        "code": "BZA",
        "name": "Vijayawada Junction",
        "city": "Vijayawada",
        "state": "Andhra Pradesh",
        "zone": "SCR",
        "division": "Vijayawada",
        "search_aliases": "vijayawada, bezawada, bza",
        "is_major": True,
        "is_junction": True,
        "platform_count": 10,
        "latitude": 16.5189,
        "longitude": 80.6208,
    },
    {
        "code": "VSKP",
        "name": "Visakhapatnam Junction",
        "city": "Visakhapatnam",
        "state": "Andhra Pradesh",
        "zone": "ECoR",
        "division": "Waltair",
        "search_aliases": "vizag, visakhapatnam, waltair, vskp",
        "is_major": True,
        "is_junction": True,
        "platform_count": 8,
        "latitude": 17.7214,
        "longitude": 83.2878,
    },
    {
        "code": "TPTY",
        "name": "Tirupati Main",
        "city": "Tirupati",
        "state": "Andhra Pradesh",
        "zone": "SCR",
        "division": "Guntakal",
        "search_aliases": "tirupati, tirumala, tpty, balaji",
        "is_major": True,
        "is_junction": True,
        "platform_count": 5,
        "latitude": 13.6289,
        "longitude": 79.4194,
    },
    {
        "code": "RU",
        "name": "Renigunta Junction",
        "city": "Tirupati",
        "state": "Andhra Pradesh",
        "zone": "SCR",
        "division": "Guntakal",
        "search_aliases": "renigunta, ru, tirupati bypass",
        "is_major": True,
        "is_junction": True,
        "platform_count": 5,
        "latitude": 13.6472,
        "longitude": 79.5167,
    },
    {
        "code": "GTL",
        "name": "Guntakal Junction",
        "city": "Guntakal",
        "state": "Andhra Pradesh",
        "zone": "SCR",
        "division": "Guntakal",
        "search_aliases": "guntakal, gtl",
        "is_major": True,
        "is_junction": True,
        "platform_count": 7,
        "latitude": 15.1728,
        "longitude": 77.3686,
    },
    {
        "code": "RTM",
        "name": "Ratlam Junction",
        "city": "Ratlam",
        "state": "Madhya Pradesh",
        "zone": "WR",
        "division": "Ratlam",
        "search_aliases": "ratlam, rtm, ratlam jn",
        "is_major": True,
        "is_junction": True,
        "platform_count": 7,
        "latitude": 23.3344,
        "longitude": 75.0375,
    },
    {
        "code": "ET",
        "name": "Itarsi Junction",
        "city": "Itarsi",
        "state": "Madhya Pradesh",
        "zone": "WCR",
        "division": "Bhopal",
        "search_aliases": "itarsi, et, hoshangabad, itarsi jn",
        "is_major": True,
        "is_junction": True,
        "platform_count": 8,
        "latitude": 22.6133,
        "longitude": 77.7634,
    },
    {
        "code": "IGP",
        "name": "Igatpuri",
        "city": "Igatpuri",
        "state": "Maharashtra",
        "zone": "CR",
        "division": "Mumbai",
        "search_aliases": "igatpuri, kasara ghat, igp",
        "is_major": False,
        "is_junction": False,
        "platform_count": 4,
        "latitude": 19.6967,
        "longitude": 73.5606,
    },
    {
        "code": "TDL",
        "name": "Tundla Junction",
        "city": "Tundla",
        "state": "Uttar Pradesh",
        "zone": "NCR",
        "division": "Prayagraj",
        "search_aliases": "tundla, firozabad, tdl",
        "is_major": True,
        "is_junction": True,
        "platform_count": 5,
        "latitude": 27.2078,
        "longitude": 78.2394,
    },
    {
        "code": "DGR",
        "name": "Durgapur",
        "city": "Durgapur",
        "state": "West Bengal",
        "zone": "ER",
        "division": "Asansol",
        "search_aliases": "durgapur, steel city, dgr",
        "is_major": True,
        "is_junction": False,
        "platform_count": 5,
        "latitude": 23.5256,
        "longitude": 87.3239,
    },
    {
        "code": "BWN",
        "name": "Barddhaman Junction",
        "city": "Bardhaman",
        "state": "West Bengal",
        "zone": "ER",
        "division": "Howrah",
        "search_aliases": "burdwan, barddhaman, bwn",
        "is_major": True,
        "is_junction": True,
        "platform_count": 8,
        "latitude": 23.2324,
        "longitude": 87.8615,
    },
    {
        "code": "KJT",
        "name": "Karjat Junction",
        "city": "Karjat",
        "state": "Maharashtra",
        "zone": "CR",
        "division": "Mumbai",
        "search_aliases": "karjat, kjt, khandala ghat base",
        "is_major": True,
        "is_junction": True,
        "platform_count": 3,
        "latitude": 18.9100,
        "longitude": 73.3283,
    },
    {
        "code": "SVJR",
        "name": "Shivajinagar",
        "city": "Pune",
        "state": "Maharashtra",
        "zone": "CR",
        "division": "Pune",
        "search_aliases": "shivajinagar, svjr, pune shivajinagar",
        "is_major": False,
        "is_junction": False,
        "platform_count": 2,
        "latitude": 18.5314,
        "longitude": 73.8446,
    },
    {
        "code": "VAPI",
        "name": "Vapi",
        "city": "Vapi",
        "state": "Gujarat",
        "zone": "WR",
        "division": "Mumbai",
        "search_aliases": "vapi, daman, vapi jn",
        "is_major": True,
        "is_junction": False,
        "platform_count": 3,
        "latitude": 20.3713,
        "longitude": 72.9044,
    },
    {
        "code": "BH",
        "name": "Bharuch Junction",
        "city": "Bharuch",
        "state": "Gujarat",
        "zone": "WR",
        "division": "Vadodara",
        "search_aliases": "bharuch, broach, narmada, bh",
        "is_major": True,
        "is_junction": True,
        "platform_count": 6,
        "latitude": 21.7051,
        "longitude": 72.9959,
    },
    {
        "code": "ANND",
        "name": "Anand Junction",
        "city": "Anand",
        "state": "Gujarat",
        "zone": "WR",
        "division": "Vadodara",
        "search_aliases": "anand, amul milk city, annd",
        "is_major": True,
        "is_junction": True,
        "platform_count": 5,
        "latitude": 22.5645,
        "longitude": 72.9289,
    },
    {
        "code": "SWM",
        "name": "Sawai Madhopur Junction",
        "city": "Sawai Madhopur",
        "state": "Rajasthan",
        "zone": "WCR",
        "division": "Kota",
        "search_aliases": "sawai madhopur, ranthambore, swm",
        "is_major": True,
        "is_junction": True,
        "platform_count": 4,
        "latitude": 25.9928,
        "longitude": 76.3578,
    },
    {
        "code": "BTE",
        "name": "Bharatpur Junction",
        "city": "Bharatpur",
        "state": "Rajasthan",
        "zone": "WCR",
        "division": "Kota",
        "search_aliases": "bharatpur, bird sanctuary, bte",
        "is_major": True,
        "is_junction": True,
        "platform_count": 3,
        "latitude": 27.2152,
        "longitude": 77.4930,
    },
    {
        "code": "FDB",
        "name": "Faridabad",
        "city": "Faridabad",
        "state": "Haryana",
        "zone": "NR",
        "division": "Delhi",
        "search_aliases": "faridabad, fdb, ncr faridabad",
        "is_major": True,
        "is_junction": False,
        "platform_count": 4,
        "latitude": 28.4089,
        "longitude": 77.3178,
    },
    {
        "code": "JL",
        "name": "Jalgaon Junction",
        "city": "Jalgaon",
        "state": "Maharashtra",
        "zone": "CR",
        "division": "Bhusawal",
        "search_aliases": "jalgaon, banana city, ajanta transit, jl",
        "is_major": True,
        "is_junction": True,
        "platform_count": 5,
        "latitude": 21.0077,
        "longitude": 75.5626,
    },
    {
        "code": "AK",
        "name": "Akola Junction",
        "city": "Akola",
        "state": "Maharashtra",
        "zone": "CR",
        "division": "Bhusawal",
        "search_aliases": "akola, akola jn, ak",
        "is_major": True,
        "is_junction": True,
        "platform_count": 6,
        "latitude": 20.7002,
        "longitude": 77.0082,
    },
    {
        "code": "BD",
        "name": "Badnera Junction",
        "city": "Amravati",
        "state": "Maharashtra",
        "zone": "CR",
        "division": "Bhusawal",
        "search_aliases": "badnera, amravati, bd",
        "is_major": True,
        "is_junction": True,
        "platform_count": 4,
        "latitude": 20.8583,
        "longitude": 77.7289,
    },
    {
        "code": "WR",
        "name": "Wardha Junction",
        "city": "Wardha",
        "state": "Maharashtra",
        "zone": "CR",
        "division": "Nagpur CR",
        "search_aliases": "wardha, sevagram, wr",
        "is_major": True,
        "is_junction": True,
        "platform_count": 4,
        "latitude": 20.7453,
        "longitude": 78.6022,
    },
    {
        "code": "BPQ",
        "name": "Balharshah Junction",
        "city": "Ballarpur",
        "state": "Maharashtra",
        "zone": "CR",
        "division": "Nagpur CR",
        "search_aliases": "balharshah, ballarpur, chandrapur, bpq",
        "is_major": True,
        "is_junction": True,
        "platform_count": 5,
        "latitude": 19.8436,
        "longitude": 79.3567,
    },
    {
        "code": "KZJ",
        "name": "Kazipet Junction",
        "city": "Warangal",
        "state": "Telangana",
        "zone": "SCR",
        "division": "Secunderabad",
        "search_aliases": "kazipet, warangal, kzj",
        "is_major": True,
        "is_junction": True,
        "platform_count": 5,
        "latitude": 17.9784,
        "longitude": 79.5217,
    },
    {
        "code": "KPD",
        "name": "Katpadi Junction",
        "city": "Vellore",
        "state": "Tamil Nadu",
        "zone": "SR",
        "division": "Chennai",
        "search_aliases": "katpadi, vellore, kpd",
        "is_major": True,
        "is_junction": True,
        "platform_count": 5,
        "latitude": 12.9698,
        "longitude": 79.1325,
    },
    {
        "code": "JTJ",
        "name": "Jolarpettai Junction",
        "city": "Jolarpettai",
        "state": "Tamil Nadu",
        "zone": "SR",
        "division": "Chennai",
        "search_aliases": "jolarpettai, jtj",
        "is_major": True,
        "is_junction": True,
        "platform_count": 5,
        "latitude": 12.5684,
        "longitude": 78.5778,
    },
    {
        "code": "SA",
        "name": "Salem Junction",
        "city": "Salem",
        "state": "Tamil Nadu",
        "zone": "SR",
        "division": "Salem",
        "search_aliases": "salem, sa, salem jn",
        "is_major": True,
        "is_junction": True,
        "platform_count": 6,
        "latitude": 11.6643,
        "longitude": 78.1460,
    },
    {
        "code": "ED",
        "name": "Erode Junction",
        "city": "Erode",
        "state": "Tamil Nadu",
        "zone": "SR",
        "division": "Salem",
        "search_aliases": "erode, ed, turmeric city",
        "is_major": True,
        "is_junction": True,
        "platform_count": 5,
        "latitude": 11.3410,
        "longitude": 77.7172,
    },
    {
        "code": "TUP",
        "name": "Tiruppur",
        "city": "Tiruppur",
        "state": "Tamil Nadu",
        "zone": "SR",
        "division": "Salem",
        "search_aliases": "tiruppur, knit city, tup",
        "is_major": True,
        "is_junction": False,
        "platform_count": 3,
        "latitude": 11.1085,
        "longitude": 77.3411,
    },
    {
        "code": "PGT",
        "name": "Palakkad Junction",
        "city": "Palakkad",
        "state": "Kerala",
        "zone": "SR",
        "division": "Palakkad",
        "search_aliases": "palakkad, palghat, pgt",
        "is_major": True,
        "is_junction": True,
        "platform_count": 5,
        "latitude": 10.7867,
        "longitude": 76.6548,
    },
    {
        "code": "TCR",
        "name": "Thrissur",
        "city": "Thrissur",
        "state": "Kerala",
        "zone": "SR",
        "division": "Thiruvananthapuram",
        "search_aliases": "thrissur, trichur, pooram city, tcr",
        "is_major": True,
        "is_junction": False,
        "platform_count": 4,
        "latitude": 10.5186,
        "longitude": 76.2144,
    },
    {
        "code": "QLN",
        "name": "Kollam Junction",
        "city": "Kollam",
        "state": "Kerala",
        "zone": "SR",
        "division": "Thiruvananthapuram",
        "search_aliases": "kollam, quilon, qln",
        "is_major": True,
        "is_junction": True,
        "platform_count": 6,
        "latitude": 8.8845,
        "longitude": 76.5954,
    },
    {
        "code": "DD",
        "name": "Daund Junction",
        "city": "Daund",
        "state": "Maharashtra",
        "zone": "CR",
        "division": "Pune",
        "search_aliases": "daund, dd, daund jn",
        "is_major": True,
        "is_junction": True,
        "platform_count": 6,
        "latitude": 18.4636,
        "longitude": 74.5807,
    },
    {
        "code": "KWV",
        "name": "Kurduvadi Junction",
        "city": "Kurduvadi",
        "state": "Maharashtra",
        "zone": "CR",
        "division": "Solapur",
        "search_aliases": "kurduvadi, pandharpur transit, kwv",
        "is_major": True,
        "is_junction": True,
        "platform_count": 4,
        "latitude": 18.0872,
        "longitude": 75.4378,
    },
    {
        "code": "KLBG",
        "name": "Kalaburagi Junction",
        "city": "Kalaburagi",
        "state": "Karnataka",
        "zone": "CR",
        "division": "Solapur",
        "search_aliases": "gulbarga, kalaburagi, klbg, gr",
        "is_major": True,
        "is_junction": True,
        "platform_count": 4,
        "latitude": 17.3297,
        "longitude": 76.8343,
    },
    {
        "code": "WADI",
        "name": "Wadi Junction",
        "city": "Wadi",
        "state": "Karnataka",
        "zone": "CR",
        "division": "Solapur",
        "search_aliases": "wadi, wadi jn",
        "is_major": True,
        "is_junction": True,
        "platform_count": 4,
        "latitude": 17.0600,
        "longitude": 76.9900,
    },
    {
        "code": "RC",
        "name": "Raichur Junction",
        "city": "Raichur",
        "state": "Karnataka",
        "zone": "SCR",
        "division": "Guntakal",
        "search_aliases": "raichur, rc",
        "is_major": True,
        "is_junction": True,
        "platform_count": 3,
        "latitude": 16.2076,
        "longitude": 77.3556,
    },
]
